### ISSUE TITLE
Instalacion de linux en otro disco

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2143-2021-2/Syllabus#1]
Hola, tengo 2 discos en mi pc, si instalo linux en uno y dejo windows en el otro no me genera problemas? Si es así, lo único que tendría que hacer es en la BIOS cambiar el disco de arranque cierto?

**Comment by JosefaPaz** [comment]
Hola! 😸 

No hay ningún problema en instalar en un disco un sistema operativo y en el otro tener Windows :)

Sobre la BIOS, si instalas Windows te saldrá al inicio los dos sistemas operativos y ahí podrás elegir con cuál quieres trabajar ^^.

Saludos!!

**Comment by Lord-Kelsier** [comment]
Muchas gracias
