### ISSUE TITLE
Duda con diferencia de versiones con Rails

### ISSUE THREAD

**Issue by crow-rojas** [IIC2143-2021-2/Syllabus#10]
Holi, tengo una duda chiquita. Seguí toda la guía de instalación y todo correcto pero por alguna razón tengo Rails 5.2.6 y no 5.2.4, habrá algún problema con eso o lo ignoro? Gracias!

![](https://i.imgur.com/cIikT0U.png)

**Comment by oretmj** [comment]
No te preocupes por eso, no debería haber ningún problema después con el proyecto.

**Comment by crow-rojas** [comment]
> No te preocupes por eso, no debería haber ningún problema después con el proyecto. 

Gracias!
