### ISSUE TITLE
Setup Base de datos Proyecto

### ISSUE THREAD

**Issue by stefanocando** [IIC2143-2021-2/Syllabus#100]
Hola
Estaba creando los archivos del proyecto en el repositorio del grupo, pero me surgió la duda de que username y clave hay que usar para la base de datos del proyecto?, dado que la estoy creando desde mi computador luego si alguien más de mi grupo quiere acceder a esta no podría porque no tienen la misma base de datos, y segundo, ¿al subir el repositorio a Heroku, como haría este para acceder a la base de datos?

**Comment by meretamal** [comment]
Hola :grin:

Las bases de datos que tienen en su computador son para su uso personal. Si es que quieren tener algunos datos en común, en un futuro podrían usar seeds (puedes investigar un poco de esto).

Para acceder a la base de datos en heroku, una vez que hiciste el deploy, podrías intentar corriendo `heroku pg:psql` en el directorio de la app que subiste.

**Comment by nicolecll** [comment]
Hola! El username y clave que tiene ir en el archivo `.env` son los tuyos, ya que posteriormente este archivo se agrega al `.gitignore `y solo es usado por la app de manera local. Respecto al conflicto que mencionas con la base de datos de tus compañeros, esto no sucede pues como mencioné, las bases de datos son netamente locales. 
Respecto a tu pregunta sobre heroku, esta plataforma tiene su propia base de datos, la cual permite agregar y eliminar cosas en linea, por lo mismo muchas veces se les pide que pueblen esta misma para facilitar la corrección. 

Espero haber sido de ayuda!
