### ISSUE TITLE
[Git] Pull entre branches - upstream

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2143-2021-2/Syllabus#101]
Hola, me surgieron dos dudas respecto a git. Si tenemos un caso como el siguiente:
![Diagrama en blanco](https://user-images.githubusercontent.com/69614275/132919672-13a09a87-ba01-4f66-a591-4b6ba1e526dc.jpeg)

Se necesita la Feature A para seguir desarrollando la Feature B. Como se haria un pull desde el master a la branch Feature B?.

Intentando averiguar como hacerlo, git me arrojo multitud de veces que debia hacer algo relacionado con `--set-upstream`. Entonces, Que es el `upstream`?

**Comment by nicolecll** [comment]
Hola! En el caso de su proyecto, cuando se tienen este tipo de situaciones, lo ideal es que como grupo trabajen con una rama intermedia llamada comúnmente como development, en la cual se van subiendo (haciendo push) los cambios funcionales mas importantes, por ejemplo la feature A. Luego si quieres tener en la feature B, lo que desarrollaste en A basta con que hagas un `git pull origin development ` y tendrías todo actualizado, pudiendo seguir en la rama de la feature B. 

Ahora, respecto a tu pregunta, `--set upstream` permite setear de manera más directa una rama remota que no has pulleado de forma local. Sin embargo, no lo recomiendo, pues cualquier pull que hagas será con tus cambios locales desprotegidos. Lo ideal es que trabajen con un flujo como el que te describí mas arriba. 

Espero haber sido de ayuda y se quedo alguna duda no dudes en volver a preguntar!

**Comment by Lord-Kelsier** [comment]
Todo claro, muchas gracias.
