### ISSUE TITLE
Problema con errores detectados por Rubocop

### ISSUE THREAD

**Issue by JJVergara** [IIC2143-2021-2/Syllabus#102]
Con mi grupo corrimos Rubocop, al inspeccionarlo, nos seguía lanzando 3 errores del tipo:
"include is used at the top level. Use inside class or module."
¿Debemos solucionar estos errores o con que no estén en el código que nosotros hemos escrito está bien?
Si no está bien, ¿Cómo se arregla?
Muchas gracias de antemano.

**Comment by nicolecll** [comment]
Hola! Cuando te refieres a 'errores' ¿a que te refieres específicamente? si es que son ofensas estas deben ser corregidas, ya que su entrega debe estar con 0 ofensas. Si es que es solo una recomendación de Rubocop, no esta demás seguirla pero no debería ser motivo de problema, de todas maneras esto puede ser conversado con su product owner. 

Espero haber sido de ayuda!

**Comment by Lord-Kelsier** [comment]
Tambien puedes hacer `rubocop --auto-gen-config` si es que te molesta que se vean los errores. Esto te genera una configuracion extra que omite esos errores.
