### ISSUE TITLE
[Administrativo] Ponderaciones 

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2143-2021-2/Syllabus#103]
Hola, en la primera clase nos dijeron que la nota final se calculaba como
```py
NF = 0.5 NI + 0.5 NP
```
Con `NI` las notas de las I's y `NP` las notas de las entregas. **Entonces, cuanto valen las Tareas?**

**Comment by OrregoSilva** [comment]
Hola! La tarea en si, no tiene nota, por lo que no sale en la formula que mencionas, sin embargo, tal como aparece en el enunciado de la misma, esta puede darte hasta 5 decimas extra en la I1.

**Comment by Lord-Kelsier** [comment]
Muchas gracias
