### ISSUE TITLE
[SETUP] Problema con configuración de Rails 

### ISSUE THREAD

**Issue by based-on-what** [IIC2143-2021-2/Syllabus#104]
Hola, estaba revisando la guía de Rails, y en un error mío escribí el comando `$ gem install rails`, actualizando a la versión más reciente, posterior a eso, desinstalé esa versión `gem uninstall rails` y volví a instalar la 5.2.4, pero al momento de revisar la versión en wsl, obtengo esto:

![errorderails](https://user-images.githubusercontent.com/62000495/132954505-e4c5c88d-db96-4a7c-8770-21a86d402535.PNG)
Mi pregunta es, ¿afecta mucho en el proyecto? ¿Qué se puede hacer a estas alturas?

Saludos y muchas gracias.

**Comment by based-on-what** [comment]
Revisé el `Gemfile` de un blog que creé con el comando `rails new blog` y la versión en ese archivo era la 6.1.4.1. :/

**Comment by meretamal** [comment]
Hola 😁 , tienes que usar la versión de la guía de setup.

Prueba desinstalando la versión 6 de rails y railties y luego instalando la versión correcta de rails.

**Comment by based-on-what** [comment]
> Hola 😁 , tienes que usar la versión de la guía de setup.
> 
> Prueba desinstalando la versión 6 de rails y railties y luego instalando la versión correcta de rails.

Muchas gracias, había olvidado desinstalar también railties, ahora al consultar por la versión tengo la 5.2.4

**Comment by based-on-what** [comment]
> Hola 😁 , tienes que usar la versión de la guía de setup.
> 
> Prueba desinstalando la versión 6 de rails y railties y luego instalando la versión correcta de rails.

Hola nuevamente, si bien instalé la versión 5.2.4, cada vez que creo aplicaciones nuevas (ahora con mis compañeros), nos sale que tenemos (tanto en consola como en el Gemfile), la versión 5.2.6 de rails, ¿es muy grave la diferencia de 0.0.2? Perdón por repetir la pregunta, pero nos pareció curioso, saludos.

**Comment by meretamal** [comment]
No, mientras se mantengan con algún _release_ de la 5.2 está bien
