### ISSUE TITLE
[SETUP] Problema al instalar Rails 5.2.4

### ISSUE THREAD

**Issue by arielkauderer** [IIC2143-2021-2/Syllabus#105]
¡Hola!

Estaba tratando de instalar Rails 5.2.4 en mi mac, ya que se me había instalado la versión 6.1. Busqué en internet y no pude solucionar mi error. Desinstalé Rails 6.1, para instalar 5.2.4 pero tampoco funcionó.

**Esto es lo que me aparece luego de ejecutar en el terminal `gem install rails -v 5.2.4`:**

Building native extensions. This could take a while...
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

current directory: /Users/arielkauderer/.rvm/gems/ruby-2.6.8/gems/mimemagic-0.3.10/ext/mimemagic
/Users/arielkauderer/.rvm/rubies/ruby-2.6.8/bin/ruby -rrubygems /Users/arielkauderer/.rvm/rubies/ruby-2.6.8/lib/ruby/gems/2.6.0/gems/rake-12.3.3/exe/rake RUBYARCHDIR\=/Users/arielkauderer/.rvm/gems/ruby-2.6.8/extensions/arm64-darwin-20/2.6.0/mimemagic-0.3.10 RUBYLIBDIR\=/Users/arielkauderer/.rvm/gems/ruby-2.6.8/extensions/arm64-darwin-20/2.6.0/mimemagic-0.3.10
rake aborted!
Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml", "/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/opt/local/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-info package for your distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
of that file.

This gem might be installed as a dependency of some bigger package, such as rails, activestorage,
axlsx or cucumber. While most of these packages use the functionality of this gem, some gems have
included this gem by accident. Set USE_FREEDESKTOP_PLACEHOLDER=true if you are certain that you
do not need this gem, and wish to skip the inclusion of freedesktop.org.xml.

The FREEDESKTOP_PLACEHOLDER option is meant as a transitional feature, and will be deprecated in
the next release.
/Users/arielkauderer/.rvm/gems/ruby-2.6.8/gems/mimemagic-0.3.10/ext/mimemagic/Rakefile:15:in locate_mime_database'
/Users/arielkauderer/.rvm/gems/ruby-2.6.8/gems/mimemagic-0.3.10/ext/mimemagic/Rakefile:39:in block in <top (required)>'
Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/arielkauderer/.rvm/gems/ruby-2.6.8/gems/mimemagic-0.3.10 for inspection.
Results logged to /Users/arielkauderer/.rvm/gems/ruby-2.6.8/extensions/arm64-darwin-20/2.6.0/mimemagic-0.3.10/gem_make.out

**Comment by PDominguezW** [comment]
Intenta con esto https://stackoverflow.com/questions/11481097/why-does-gem-install-rails-fail/11481805. Si no te funciona avisame.

**Comment by arielkauderer** [comment]
No me funciona. Me sale que el comando apt-get no existe.

**Comment by CamilaArgomedo** [comment]
Tengo el mismo problema!!

**Comment by antoniacaceres** [comment]
yo también tengo el mismo problemaa!

**Comment by antoniacaceres** [comment]
al final lo pude arreglar instalando la version 5.2.6 que era la compatible con mi software (macOS Mojave)
