### ISSUE TITLE
error deploy heroku

### ISSUE THREAD

**Issue by Franco1208** [IIC2143-2021-2/Syllabus#108]
Hola!!
Al hacer el push en heroku de mi proyecto me tira el siguiente error:

![image](https://user-images.githubusercontent.com/69912991/133139860-b335ac21-a6d2-4184-afc6-61f5957deeec.png)

De antemano, muchas gracias!

**Comment by oretmj** [comment]
Hola, el problema es que no te reconoce la app (o su lenguaje, tal como dice ahi). Supongo que dentro del repositorio que pusheaste a tu heroku hay un carpeta donde se encuentra la app, ese es el problema. Para solucionarlo tienes que tener la app en la raíz del repositorio, trata sacando todos los archivos dentro de esa carpeta. 

Asi estaria mal:
-repositorio
    -proyecto
        -app
        -bin
        -.....
        .....
        .....
        (resto de los archivos de la app)

Trata teniendolo asi:
-repositorio
    -app
    -bin
    -......
    .....
    (resto de los archivos de la app)


Ojala se entienda y te funcione.
