### ISSUE TITLE
Error en el uso de Ruby

### ISSUE THREAD

**Issue by JoseTomasSoto** [IIC2143-2021-2/Syllabus#11]
Hola!
Ya instalé todo de acuerdo a las instrucciones, y me sale que efectivamente estoy en rails y que se instaló todo correctamente, pero a la hora de correr un archivo .rb no me interpreta Ruby.
He probado varias cosas, incluso la extensión Code Runner, pero nada funciona.
Agradezco de antemano su disposición.
Muchas Gracias!

"
ruby : El término 'ruby' no se reconoce como 
nombre de un cmdlet, función, archivo de script 
o programa ejecutable. Compruebe si escribió    
correctamente el nombre o, si incluyó una ruta  
de acceso, compruebe que dicha ruta es correcta 
e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ ruby hola_mundo.rb
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (  
   ruby:String) [], CommandNotFoundException     
    + FullyQualifiedErrorId : CommandNotFoundEx  
   ception
"

Muchas gracias!

**Comment by OrregoSilva** [comment]
Hola!
Instalaste ruby y rails con wsl? Si es asi, debes ejecutar los archivos de ruby en la consola de ubuntu, ya que es ahi donde se instalo todo. Para cambiarte de consola escribe `wsl` y luego `ruby hola_mundo.rb`, eso deberia funcionar!

**Comment by JoseTomasSoto** [comment]
Gracias! Ahí funcionó!
