### ISSUE TITLE
FATAL:  database <nombre_proyecto> does not exist

### ISSUE THREAD

**Issue by franciscares** [IIC2143-2021-2/Syllabus#110]
Hola!
Tengo una duda, un compañero creó el proyecto y cuando intento abrirlo en mi pc me sale este error:

ActiveRecord::NoDatabaseError (FATAL:  database <nombre_proyect> does not exist):

y no corre. Antes de correrlo hice el db create, pero no funciona.

**Comment by nicolecll** [comment]
Hola! Intenta con `rails db:drop` y luego con ` rails db:create`.

**Comment by franciscares** [comment]
Hola! Corrí eso, y leyendo la terminal sale esto
ERROR:  permission denied to create database
antes del error anterior sale ese.

**Comment by nicolecll** [comment]
Creo que puede ser un error con postgres, accede a la consola de postgres con 
`sudo -u postgres -i y luego corre  `postgres@host:~$ psql`. Después modifica el permiso del host con `postgres=# ALTER USER new_user CREATEDB;`
Cuentame si te sirve

**Comment by franciscares** [comment]
Ta funcionó! Gracias :)
