### ISSUE TITLE
Problema Commit RuboCop 

### ISSUE THREAD

**Issue by sigualt** [IIC2143-2021-2/Syllabus#111]
Hola! Tengo un problema al tratar de hacer un commit tras haber instalado rubocop en mi proyecto. Lo que pasa es que hago git add y me sale que hay otra operación de git en proceso, al hacer el git status me sale que el archivo .rubocop.yml es untracked, no se que significa. Adjunto una foto del error tras hacer un git add . .Muchas gracias!

<img width="1080" alt="2021-09-14 (2)" src="https://user-images.githubusercontent.com/69644598/133293060-dd1d1253-ce94-427e-b7a7-728b1afb9274.png">

**Comment by JosefaPaz** [comment]
Hola!

Si en el git status te aparece que .rubocop.yml es untracked puede que esté añadido en el .gitignore! Si lo revisas y se encuentra ahí faltaría sacarlo y podrías subirlo al repo :)

Quedo atenta!
