### ISSUE TITLE
Dudas con heroku

### ISSUE THREAD

**Issue by Piolawa** [IIC2143-2021-2/Syllabus#113]
Hola! Tengo 2 consultas:
1.- En la página de heroku quería abrir la página que creamos con el botón “open App” y me sale el siguiente error:

The page you were looking for doesn’t exist.
You may have mistyped the adress or the page may have moved.
If you are the application owner check the logs for more information.

2.- Al hacer push de heroku debería haber un archivo en github, no? Es que no aparece nada nuevo. :(

**Comment by oretmj** [comment]
Hola, 
1.- Supongo que hiciste un push al heroku del "Welcome in Rails", es decir de la app con la vista predeterminada de Rails. Si es así es normal que te indique ese error porque Heroku no puede hacer la relación con la ventana predeterminada, sino que busca según el link default que tengas asignado en las rutas, que en el caso de una nuevo app es ninguno. 

Aca hay un link que lo explica y como podrias solucionarlo para que te aparesca el "Welcome in Rails": https://stackoverflow.com/questions/42770586/rails-app-on-heroku-doesnt-display-welcome-aboard-page

2.- El push al heroku no se ve en el github porque funcionan como puntos remotos distintos, es decir lugares donde se guardan tus archivos distintos. En detalle no sabría decirte como ver los push en heroku, pero puedes, en _Activity_ de tu app en heroku, ver el ultimo deploy hecho. 

Ojala te sirva etsa explicación.
