### ISSUE TITLE
Configuración Heroku

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2143-2021-2/Syllabus#114]
Hola :), tengo un par de dudas.

1. Cuando hicimos el setup creamos un proyecto en Ubuntu. Me tiene confundido si para esta entrega debemos usar ese mismo creado (https://github.com/IIC2143-2021-2/Syllabus/tree/main/Gu%C3%ADas/Setup/Ubuntu) o se debe crear otro. Si se usa el mismo, no estoy entendiendo como pasarlo al repo que nos dieron. Si se debe crear uno nuevo, no estoy entendiendo desde donde crearlo (repo asignado que se asocia a heroku??).

2. Con respecto a Heroku, una vez creado el proyecto y pusheado en repo asignado, debo hacer log in desde la ruta en donde esta el proyecto en mi computador ??

Vi la ayudantía 2 pero quedé medio confundido.

**Comment by oretmj** [comment]
Hola, 

1. Habrían 2 opciones, pueden crear un nuevo repo iniciando desde le paso 8 de la guía que mandaste o si quieren pueden copiar un proyecto que ya tengan creado (el del setup en tu caso) y pegarlo dentro del repositorio.  Tengo 2 consejos acá, en el paso del archivo _.env_ **recuerda agregarlo el _.gitignore_** (es importante para evitar problemas y que tus compañeros no te sapeen tus claves). El otro consejo es que si creas el proyecto o lo copias, tengas los archivos en la raíz del repositorio, es decir que al abrir la carpeta del repositorio se encuentre la app y no una carpeta donde este la app (puedes hacerlo simplemente moviendo las cosas hacia abajo y esto te podría ahorrar problemas con el Heroku ya que no reconoce las apps si hay una carpeta entremedio)

2. El log in del Heroku se puede hacer en cualquier parte, es simplemente para iniciar la sesión. Lo deberias hacer antes de pushear al Heroku y eso te deberia pertmitir usar los comandos de _heroku git_. 

Ojala esto te aclare tus dudas.

**Comment by dsepulveda3** [comment]
Gracias ! 
La duda que me queda es como abrir la ruta del repo local desde ubuntu para hacer el rails new <nombre proyecto> --database=postgresql.

Actualmente estoy parado en el repo local de mi grupo desde la cmd y cuando pongo rails new <nombre proyecto> --database=postgresql no me funciona la creación del proyecto

**Comment by dsepulveda3** [comment]
Oka gracias. Ultima pregunta.
DB_USER=myuser
DB_PASSWORD=mypassword

que debo poner acá en el archivo .env siendo que las 3 personas del grupo usaremos repo

**Comment by oretmj** [comment]
Ahí haces igual que en el setup, pones tus datos, pero por eso te digo que lo agregues en el _.gitignore_ para que no se suba al repo y los otros lo vean.  Si lo agregas en el _.gitignore_ no se va a subir al realizar los git add, commit y push. 
La idea de eso es que tu app localmente pueda acceder a tu sql para trabajar la base de datos, por eso solo es necesario en tu computador el archivo _.env_.
Si algo de esto no te quedo claro dime.
