### ISSUE TITLE
Complicación tratando de hacer CRUD

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2143-2021-2/Syllabus#118]
Hola, esperando que estén bien, me pasaba que tratando de seguir la ayudantía de CRUD y hacer la misma página que Martín hacía de los juegos, luego de ya haber creado el modelo Game, modificado el archivo new.html de views, agregado los métodos new y create en el archivo games_controller, cuando ejecuto rails s no me aparece el formulario para crear un nuevo juego, sino la aplicación mínima de mi grupo creada en la primera entrega. Sorry si es muy mala issue por lo ambigüo, pero en vdd no sabría qué más detalles dar. Cualq orientación sobre qué podría ser que no esta actualizando el local host la agradecería.

**Comment by OrregoSilva** [comment]
Hola! De casualidad al abrir la pagina, sigues en la pagina de inicio? De ser así, recuerda que tienes que dirigirte con la url o un path a las vistas que estas creando, por default se crean como `/{model}/{method}`, por ejemplo, la ruta de la ayudantía era `localhost:3000/games/new`.

**Comment by JuanpaBC** [comment]
Hola, disculpa se me olvidó contestar, pero lo pude resolver muchas gracias!
