### ISSUE TITLE
Error al crear base de datos de proyecto Rails

### ISSUE THREAD

**Issue by maxcorvalan** [IIC2143-2021-2/Syllabus#12]
Cuando intento crear la base de datos para el proyecto rails, me arroja el siguiente error:

could not connect to server: No such file or directory
Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
Couldn't create '<Juntapp>_development' database. Please check your configuration. rails aborted!
PG::ConnectionBad: could not connect to server: No such file or directory
        Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

Juntapp es el nombre del proyecto, modifiqué el archivo database.yml y creé el archivo .env

**Comment by PDominguezW** [comment]
Recuerda que primero debes iniciar postgresql. Para eso debes utilizar el comando `sudo service postgresql start` e ingresar tu clave.
