### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2143-2021-2/Syllabus#120]
Hola, tengo listo mi creador de usuarios, sin embargo al correrlo no me está dando la vista. He revisado varias veces y no se que puede estar mal. Lo que estoy haciendo es lo siguiente:

1. Luego de tener listo el código en vscode presiono control+S para guardar.
2. Voy a mi consola y corro "sudo service postgresql start"
3. Luego corro "rails db:migrate"
4. Por ultimo corro "rails server"
![image](https://user-images.githubusercontent.com/62180259/135358933-562eb793-3c44-4fd9-adef-ad031dfb01fa.png)

5. Finalmente ingreso a "http://localhost:3000/usuarios/new"
![image](https://user-images.githubusercontent.com/62180259/135358894-a93d99cd-1940-4041-84b6-b5769b95a2b9.png)

**Comment by nicolecll** [comment]
Hola, aun tienes el error? y si es asi, puede adjuntar un screenshot?

**Comment by dsepulveda3** [comment]
Sii. Todavía no logro solucionarlo

**Comment by dsepulveda3** [comment]
Ya logré solucionarlo. Gracias de todas formas
