### ISSUE TITLE
Error en la instalación de Ruby en mac

### ISSUE THREAD

**Issue by panchotarud** [IIC2143-2021-2/Syllabus#13]
Hola! Estaba tratando de instalar ruby en mac y me aparece este error:

**Error running '__rvm_make -j12',
please read /Users/franciscotarud/.rvm/log/1629684346_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.**

Que puedo hacer?

**Comment by tatanramos** [comment]
Hola! Podrías mandar qué comando usaste en la consola?

De todas formas podrías probar con:

```

> rvm reload
> rvm install ruby-2.6.6

```
Otra cosa que podría servir puede ser este [link](https://github.com/rvm/rvm/issues/4484#issuecomment-470707209), donde se da una solución en mac para el error en el make (en caso de que te este fallando ahí)

Quedo atento cualquier cosa!

**Comment by panchotarud** [comment]
Traté con esos comandos y me tira el mismo error:( con el link logre instalar ruby 2.5.0, pero no puedo utilizarlo ya que en la version de rails q instale, me pide mínimo ruby 2.6.3. No se que hacer

**Comment by tatanramos** [comment]
Encontré una solución para un error similar (_**Error running '__rvm_make -j8**_), quizás prueba esto a ver si te funciona
```
sudo mv /usr/local/include /usr/local/include_old
rvm install 2.6
```

**Comment by panchotarud** [comment]
Tampoco:( me dice que no existe el directorio o el archivo

**Comment by tatanramos** [comment]
Chuta, vamos a prueba y error nomás parece jajaja
Por lo que estoy entendiendo puede haber un problema en el archivo make.log, podrías probar con esto a ver que tal (puedes cambiar la versión de ruby por la 2.6.6, aunque la 2.6.3 debería ser suficiente):
`rvm install "ruby-2.6.3" --with-out-ext=fiddle`

**Comment by panchotarud** [comment]
Con ese pude! Muchas graciass
