### ISSUE TITLE
Versión de wsl

### ISSUE THREAD

**Issue by railira** [IIC2143-2021-2/Syllabus#14]
Hola!
¿Es necesario tener como predeterminada la versión 2 de wsl? Esto porque si dejo esta versión Ubuntu me arroja el error 0x80370102, para el cual ya busque varias soluciones y la única que me resultó fue la de dejar como predeterminada la versión 1 de wsl.

**Comment by PDominguezW** [comment]
Quedate con la version 1 de wsl.
