### ISSUE TITLE
POST, DELETE request externos

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2143-2021-2/Syllabus#143]
Hola, tengo una pregunta. Supongamos que tenemos en la pagina un boton para eliminar a un usuario. Si queremos que solo pueda eliminar un perfil un administrador o el dueño de ese perfil, seria suficiente colocar:

```rb
if (current_user == @user || @user.is_admin)
  mustra_el_boton
end
```
En otras palabras, alguien podria hacer un POST o DELETE request sin las herramientas que le proveemos en la pagina para hacerlo (botones, en este caso)?.

**Comment by chineseJack564** [comment]
Lo que haces alli es un verificacion en el front-end, dependiendo de lo que te pide tu ayudante. Puedes necesitar implementar una verificacion del lado servidor, haciendo algo asi en el controlador:
`if (current_user == @user || @user.is_admin)
  acciones de delete
end`

**Comment by Lord-Kelsier** [comment]
muchas gracias
