### ISSUE TITLE
Problema/duda paso 9: falta de config/database.yml (ubuntu)

### ISSUE THREAD

**Issue by Pabloski100** [IIC2143-2021-2/Syllabus#15]
Hola! tengo una duda en este paso, entiendo que la carpeta del proyecto es la que se creo en el paso 8, sin embargo, dentro de esa carpeta no tengo el directorio que se menciona en el paso 9 (`config/database.yml `) solo tengo algunos archivos de ruby, un readme y otro par de archivos.

Debería tener ese directorio ahí o entendí mal el paso?

**Comment by felipefuentesporras** [comment]
Debería estar dentro de tu proyecto. Adjunta una foto de los archivos que te salen en el proyecto.

**Comment by Pabloski100** [comment]
Me sale esto estando en vscode
![Captura de pantalla de 2021-08-23 01-28-42](https://user-images.githubusercontent.com/80791272/130395244-d0d94ba5-a3c7-4375-b7cc-9197ad9420ab.png)

**Comment by felipefuentesporras** [comment]
Parece que el problema es que no tienes instalado git en Ubuntu. 

https://stackoverflow.com/questions/59363292/rails-new-is-not-generating-any-of-my-projects-folders

En esta issue ven el mismo problema que tienes. Instala git en Ubuntu usando:

sudo apt install git

Y intenta crear la app de nuevo. Si ya tenías git instalado, intenta crear la app y manda una foto de lo que te aparece en consola.

**Comment by Pabloski100** [comment]
Hola! Perdón por la demora, efectivamente, era eso, muchas gracias! :D
