### ISSUE TITLE
Problemas set up Mac pasos 3 y 4

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2143-2021-2/Syllabus#17]
Hola, la consola me retorna los siguientes errores en los pasos mencionados (por lo que el paso 5 tampoco me funciona)
Paso 3:
![paso3](https://user-images.githubusercontent.com/62023649/130485028-3a953604-77dc-4c14-be51-d4b6102610ff.png)

Paso 4:
![paso4](https://user-images.githubusercontent.com/62023649/130485058-e361d32a-04a4-461d-90ab-e1f6db2be2fc.png)

**Comment by pabloalvarez67** [comment]
Segun yo, tampoco me funciona el paso 2: **brew install gnupg**

**Comment by conyortizsimpson** [comment]
Hola! Ejecuta los dos primeros pasos de la instalación de nuevo para asegurarnos de que estés en la última versión de brew. 

Si esto no funciona trata colocando este código en el terminal `git -C $(brew --repo homebrew/core) checkout master` ([más información aquí](https://stackoverflow.com/questions/68089836/brew-tap-mongodb-brew-results-in-fatal-could-not-resolve-head-to-a-revision
)). Esto debería arreglar el error

**Comment by pabloalvarez67** [comment]
> Hola! Ejecuta los dos primeros pasos de la instalación de nuevo para asegurarnos de que estés en la última versión de brew.
> 
> Si esto no funciona trata colocando este código en el terminal `git -C $(brew --repo homebrew/core) checkout master` ([más información aquí](https://stackoverflow.com/questions/68089836/brew-tap-mongodb-brew-results-in-fatal-could-not-resolve-head-to-a-revision)). Esto debería arreglar el error

Me sirvió! gracias.
Lo que si, ahora no pude instalar rails.

![Captura de Pantalla 2021-08-23 a la(s) 10 19 45 p  m](https://user-images.githubusercontent.com/62023649/130545692-960f3f67-e688-4906-99ed-381b932ce84a.png)

No se si sabes que puede ser? o quizas el gem ya viene incluido, algo entendi de lo que lei en la issue:
https://github.com/IIC2143-2021-2/Syllabus/issues/8

**Comment by conyortizsimpson** [comment]
¿Puedes tratar correr `brew install shared-mime-info
`? [info](https://stackoverflow.com/questions/66823608/cant-install-rails-on-mac-os-catalina) Creo que eso lo solucionaría.

A la próxima si quieres hacer otra pregunta no relacionada al error que publicaste puedes hacer otra issue porfis, para que los demás puedan encontrar la solución si les aparecen :)
