### ISSUE TITLE
Error al crear base de datos

### ISSUE THREAD

**Issue by jorgemouat** [IIC2143-2021-2/Syllabus#18]
![image](https://user-images.githubusercontent.com/62305130/130512579-b95ccad3-9a30-496e-a945-fa2b4ca3df15.png)
Por que puede ser que me salga "Permission denied"? Vi una issue parecida pero no tenía este error. Gracias

**Comment by jorgemouat** [comment]
Si corrí ese comando pero aún me sigue tirando el mismo error

**Comment by festelle** [comment]
En el setup pusiste tus credenciales de psql para que pudiera acceder?

**Comment by jorgemouat** [comment]
En el .env? Ahí si los puse

**Comment by festelle** [comment]
Este post de stackoverflow te puede ayudar: https://stackoverflow.com/questions/8465508/can-not-connect-to-local-postgresql

**Comment by OrregoSilva** [comment]
Es posible que se trate de problemas con el puerto, si lo fuera, trata de ejecutar `cat /etc/postgresql/10/main/postgresql.conf` y muéstrame el output de la sección `CONNECTIONS AND AUTHENTICATION` (es de las primeras).

**Comment by jorgemouat** [comment]
![image](https://user-images.githubusercontent.com/62305130/130529974-acb27da1-8ce5-4efe-976a-f68968e96887.png)

**Comment by OrregoSilva** [comment]
Efectivamente tienes mal seteado el puerto, esta en 5433 y no 5432, para cambiarlo sigue estos pasos/comandos:

- `sudo nano /etc/postgresql/10/main/postgresql.conf`  Esto te abrirá un editor de texto en la misma consola.
- En la misma sección de antes, busca la linea que dice `port = 5433` y cámbiala por `port = 5432`
- Para salir, `ctrl + x`, luego `y` para confirmar los cambios y finalmente `enter`.
- `cat /etc/postgresql/10/main/postgresql.conf` nuevamente para verificar que se hizo el cambio.

De casualidad tenias PostgreSQL instalado de antes en Windows?

**Comment by jorgemouat** [comment]
Se cambió y está guardando pero me sigue tirando el mismo error. Si lo tenía instalado de antes.

**Comment by OrregoSilva** [comment]
Si lo tienes de antes tienes que detener el servicio (en Windows) o en su defecto desinstalarlo, para detenerlo, `win + r` desde cualquier lugar como si fuera un `ctrl + c`, escribe `services.msc` y al dar aceptar busca `postgresql-x64...`, click derecho y detener, luego cierra las consolas que tengas, abre una nuevamente, `sudo service postgresql start` y trata de crear la db.

**Comment by jorgemouat** [comment]
Con detener no me funcionó pero al desinstalarlo y volver a instalar si! Muchas gracias, te pasaste!

**Comment by sbersani69** [comment]
Hola , 
Trato de poner el comando para cambiar el puerto pero me dice que la carpeta no existe.
(comando sudo nano /etc/postgresql/10/main/postgresql.conf)

adjunto imagen

![image](https://user-images.githubusercontent.com/56396783/130632016-85f0f451-553a-4d54-98d1-56220f03adbc.png)

**Comment by sbersani69** [comment]
Hola,
Trato de utilizar el comando para acceder a cambiar el puerto donde está postgres pero me dice que el directorio no existe(adjunto comando y foto)
![image](https://user-images.githubusercontent.com/56396783/130632801-67192754-8cdf-47e5-800b-d63a458b2b90.png)

**Comment by OrregoSilva** [comment]
En ese caso entra a la consola de PostgreSQL (`sudo -u postgres psql`) y ejecuta `SHOW HBA_FILE;`, debería salir algo así:
```
postgres=# SHOW HBA_FILE;
              hba_file
-------------------------------------
 /etc/postgresql/10/main/pg_hba.conf
(1 row)
```

Ahí puedes ver la ruta de donde debería estar (tienes que omitir el `pg_hba.conf`)

**Comment by sbersani69** [comment]
Tampoco me funciona, pongo **sudo -u postgres psql** y me dice 
_psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5433_
