### ISSUE TITLE
Paso 9 SetUp

### ISSUE THREAD

**Issue by cicarrasco5** [IIC2143-2021-2/Syllabus#2]
Hola! Estuve realizando los pasos del set up para Mac después de la ayudantía, cree una carpeta de prueba y antes de seguir con el paso 7 cambie la ubicación de la carpeta (les menciono sobre el cambio de ubicación por si tiene que ver con eso), luego seguí en vscode sin problema hasta el último paso donde me arroja este error después de mostrarme el Traceback (most recent call last) :

/Users/camilacarrasco/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'racc' (~> 1.4) among 121 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/camilacarrasco/.rvm/gems/ruby-2.6.3:/Users/camilacarrasco/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0', execute `gem env` for more information

En base a eso intenté instalar la gema con un comando recomendado "gem pristine racc --version 1.5.2" a lo que me arrojaba
ERROR:  While executing gem ... (Gem::Exception)
    Failed to find gems ["racc"] = 1.5.2

Ya no sé que hacer :c

**Comment by conyortizsimpson** [comment]
Hola! Parece que la gema no se descargó bien. Te recomiendo seguir:
1. Abre el terminal
2. Escribe `gem install racc -v 1.4.14`
3. Dentro de tu carpeta donde creaste el proyecto, abre el terminal desde aquí y ejecuta `bundle install`

Así se te debería instalar la gema. En el caso que no funcione después de esto, ¿cuándo tira el error? ¿después de correr `rails s`?
