### ISSUE TITLE
Problema en paso 4 MacOS

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2143-2021-2/Syllabus#20]
Al tratar de instalar rails me da un error. Busqué en Google y no encontré la solución.

<img width="871" alt="Screen Shot 2021-08-23 at 19 52 06" src="https://user-images.githubusercontent.com/62315390/130533949-73416d54-b1c7-4ab4-bd4c-fbdd2e3542dd.png">

**Comment by nicolascamhi** [comment]
Solucionado!

**Comment by JosefaPaz** [comment]
Hola @nicolascamhi !

Podrías comentarnos cómo lo solucionaste por si a algún otro estudiante le ocurre el mismo problema?

Gracias y me alegro que se solucionara!!

**Comment by nicolascamhi** [comment]
Hay que correr

brew install shared-mime-info
