### ISSUE TITLE
Consulta paso 9: Dudas sobre archivo database.yml (no puse nombre)

### ISSUE THREAD

**Issue by Pabloski100** [IIC2143-2021-2/Syllabus#21]
Hola! Quería consultar que tan grave es un detalle que se me paso mientras hacia el paso 9, en lo que había que copiar y pegar, no cambie las lineas que eran `<nombre proyecto>_development`, así que me quedaron cosas con ese nombre, afecta algo eso? Es peligroso cambiarlo después de haber hecho todos los pasos?

**Comment by domingo2000** [comment]
Hola, te recomiendo que cambies todos los archivos del proyecto como indica la guía pues así te aseguras que no se suben a github las vairables de entorno como tu username y password de la base de datos. Si es que no lo cambiaste en el proyecto que acabas de hacer, simplemente borra la carpeta con tu proyecto y crea uno nuevo siguiendo la guía desde el paso 8 en adelante.

**Comment by Pabloski100** [comment]
Logre realizar todos los pasos bien, gracias!
