### ISSUE TITLE
Problema paso 8:  No such file or directory 

### ISSUE THREAD

**Issue by jofigl** [IIC2143-2021-2/Syllabus#22]
Hola! Estoy intentando hacer el paso 8 desde la consola de ubuntu (tengo windows) y al momento de querer ejecutar el comando `rails new <nombre proyecto> --database=postgresql` me dice "No such file or directory", refiriéndose al nombre que le intento poner al proyecto. He intentado desinstalando la consola y no logro ver donde está mi error :(.

Quedo atenta y muchas gracias :)

**Comment by nicolecll** [comment]
Hola! Solo para descartar, cuando escribes el comando `rails new <nombre proyecto> --database=postgresql ` ¿lo haces con <> ?, ya que debe ser simplemente el nombre de tu proyecto.

**Comment by juan-palma-1** [comment]
Hola buenas yo tengo el siguiente problema en este paso:
Al crear la nueva carpeta para el proyecto me arroja el siguiente error: 
![image](https://user-images.githubusercontent.com/69826716/130708652-023444c9-1ad2-41ee-9fac-2a6ea90730e2.png)
Por lo que se me crea la carpeta correctamente pero faltan las subcarpetas dentro. La subcarpeta config no está por lo que no puedo seguir adelante con el paso 9, adjunto foto de la carpeta creada, muchas gracias de antemano.
![image](https://user-images.githubusercontent.com/69826716/130708755-9f38ef84-9675-40ab-b9bc-de60b6ec59d2.png)

**Comment by felipefuentesporras** [comment]
Revisa la issue#15. Parece que tienes el mismo problema.

**Comment by juan-palma-1** [comment]
Gracias Felipe, era eso me faltaba instalar git en ubuntu.

**Comment by Franco1208** [comment]
Hola jofil!! A que paso tuviste que volver, porque a mi me sale el mismo error y no entendi como solucionarlo, en una de esas me paso lo mismo que a ti.
