### ISSUE TITLE
Problemas creando la base de datos (Paso 10)

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2143-2021-2/Syllabus#23]
Hola. Al momento de crear la base de datos del Paso 10 dentro de la carpeta del proyecto me tira varios errores de instalación que no se como solucionar :(
Al hacer `bundle install` me tira esto (entre otras cosas):
![image](https://user-images.githubusercontent.com/68198662/130672412-76bd53b7-a885-4e91-a02b-b1b340082609.png)
![image](https://user-images.githubusercontent.com/68198662/130672463-5ea343df-0f8c-4d31-b471-7668e7c6db11.png)
Luego ingreso el comando que me indican, y ocurre esto:
![image](https://user-images.githubusercontent.com/68198662/130672806-494e1a3b-5dc2-4712-8014-8c72a439ac36.png)

Alguna idea a que se puede deber esto?

**Comment by Gsalinas1506** [comment]
Me di cuenta de este error cuando intenté hacer `rails db:create`
![image](https://user-images.githubusercontent.com/68198662/130673226-725d139d-0bf3-4f50-b106-4b799402580a.png)

**Comment by felipefuentesporras** [comment]
Podrías intentar con lo que en la consola se muestra que se instale. Intenta correr esto en consola:
gem install pg -v '1.2.3'

Después, intenta de nuevo el bundle y rails db:create

**Comment by Gsalinas1506** [comment]
ya lo intenté, y me tira esto (ERROR: Failed to build gem native extension) :(
![image](https://user-images.githubusercontent.com/68198662/130706650-02982c51-81e7-4a9c-bf6e-c262cefc105d.png)

**Comment by felipefuentesporras** [comment]
En esta issue ven el problema que estas teniendo:
https://stackoverflow.com/questions/4827092/unable-to-install-pg-gem
Intenta usando:
sudo apt-get install libpq-dev
Y luego prueba de nuevo

**Comment by Gsalinas1506** [comment]
Bueena ahí si me resultó! Muchas gracias
