### ISSUE TITLE
Problemas paso 11

### ISSUE THREAD

**Issue by railira** [IIC2143-2021-2/Syllabus#24]
Hola, llegue hasta el paso 11 siguiendo al pie de la letra la guía, pero al poner el código en la consola y apretar el link para el local host me encuentro con la siguiente página
![error](https://user-images.githubusercontent.com/62022050/130874523-1e78e743-8150-4fe2-9f7c-b8e263b6d134.PNG)
He probado diferentes opciones pero no se me ocurre que puede ser lo que está fallando.

**Comment by BibarelUsedFly** [comment]
@railira lo solucionaste? T-T

**Comment by railira** [comment]
Si! problema solucionado. 
El problema partía porque en un ramo anterior me pidieron descargar un servidor de psql y este ocupaba el puerto, hubo que desinstalar eso y volver a hacer todo desde el principio.

**Comment by BibarelUsedFly** [comment]
Oh no, _todo_ de nuevo? D:
Osea es ir a panel de control desinstalar psql y luego repetir todo?

**Comment by BibarelUsedFly** [comment]
No me funcionó :::c
