### ISSUE TITLE
Error en paso 4 rails

### ISSUE THREAD

**Issue by fedezang** [IIC2143-2021-2/Syllabus#3]
Hola!
Tengo un problema en el paso 4 del SetUp en Mac, al correr en la terminal:
*gem install rails -v 5.2.4*

Me tira como error lo siguiente:
![Captura de Pantalla 2021-08-21 a la(s) 01 03 30](https://user-images.githubusercontent.com/62078222/130311135-4936a444-11c1-45fc-8d10-464351e25d4c.png)

Como podría arreglar esto?

**Comment by catalina-ramirez** [comment]
Hola! Por lo que veo, te está pidiendo que instales shared-mime-info. Para eso, debes usar el comando `brew install shared-mime-info`. Luego de hacer eso, prueba nuevamente el paso 4 y dime si te funciona!

**Comment by fedezang** [comment]
Ahora si me funcionó, muchas gracias!
