### ISSUE TITLE
Error en paso 3

### ISSUE THREAD

**Issue by magdalenanario** [IIC2143-2021-2/Syllabus#33]
Hola! Al poner el código del paso 3 me aparece este error
![image](https://user-images.githubusercontent.com/62227994/131040162-408ede15-a56d-44af-bc5e-c9701d69eecc.png)

Vi en otra issue que a alguien le aparecía ese mismo error y recomendaron otro código que también lo pobré pero aparece el siguiente error
![image](https://user-images.githubusercontent.com/62227994/131040301-1af2226e-c907-4dfc-a773-d1d2ba4a2252.png)
¿Que puedo hacer?

**Comment by enriquerussi** [comment]
> Mee pasa lo mismo :/. Y después al ejecutar **curl -sSL https://get.rvm.io | bash -s stable**, me tira esto:
> ![image](https://user-images.githubusercontent.com/62180259/131160440-1d5b17f9-c8ac-486c-8784-278efd3fa6ee.png)

Hola, estoy en la misma posición. ¿Lograron resolver esto?
