### ISSUE TITLE
[Tarea] - Duda propinas

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2143-2021-2/Syllabus#35]
Hola, las propinas de cada mesa las calculamos sacando el 10% del total de la suma del valor de los platos de esa mesa?

Y otra duda, se supone que la clase mesero tiene un atributo int de propina. Qué significa? si según enunciado las propinas no se calculan con ese atributo... o ese atributo del mesero hay que irlo actualizando con las propinas ganadas?

Gracias.

**Comment by pabloalvarez67** [comment]
> Hola!
> 
> Como dice en la sección 5. "Calcular total cliente", el total que cada cliente paga es: costo de sus platillos pedidos + 10% del costo total a pagar por el cliente (propina).
> 
> Sobre tu segunda duda, en la sección 7. "Calcular propina", se explica lo siguiente: "La propina del mesero n corresponde a la suma de las propinas de cada mesa que atiende" , por lo que así se debe calcular. (En la misma sección sale un ejemplo).

Perfecto, y ahora esa propina calculada para ese mesero, debiese afectar al atributo propina del objeto mesero? debiese sumarse a lo que tiene actualmente?
Gracias!

**Comment by JosefaPaz** [comment]
@pabloalvarez67 Hola! Sii, debería sumarse al que tiene actualmente! :)
