### ISSUE TITLE
bundle install paso 8

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2143-2021-2/Syllabus#36]
Hola, estoy ejecutando los comandos desde root@. Antes de correr el "bundle install" (al correr "rails new <nombre proyecto> --database=postgresql"), la consola me tiro esto:
![image](https://user-images.githubusercontent.com/62180259/131165356-e728d3d9-5b63-43a8-b004-60ace8fa6f1f.png)

Que hago en este caso ? Siendo que sale que ejecutar "bundle install" desde root podría traer problemas.

**Comment by domingo2000** [comment]
Los comandos que se usan para el proyecto correlos desde la carpeta de tu proyecto, es decir
`rails new <nombre_proyecto> --database=postgresql`  si lo corres en root porque es para crear el proyecto
luego haces `cd <nombre_proyecto>` para ir al directorio de tu proyecto
Y ahi si corres 
`bundle install` para instalar las dependencias
`rails db:create` para crear la base de datos de tu proyecto
`rails s` para correr la aplicacion el localhost
