### ISSUE TITLE
[Tarea]- Implicancias de instrucciones a ejecutar

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2143-2021-2/Syllabus#38]
Hola! Estoy un poco enredado en cómo es el flujo del programa, entiendo que debemos cargar archivos con datos en las clases, pero a la hora de ejecutar instrucciones quería saber si, por ejemplo, se tiene "top_meseros", esto implica que debo calcular la propina de los meseros antes de hacer el top (creo que sí), pero como las instrucciones se repiten, ¿debo volver a calcular la propina de los meseros? si, en teoría, ya se calcularon una vez para las mesas. Porque no me hace sentido cobrar dos veces, esto mismo para las otras instrucciones 😢 Gracias de antemano!

**Comment by JosefaPaz** [comment]
Hola James!

Para hacer el top_meseros no es necesario calcular la propina antes, ya que si te fijas esta se va actualizando solo cuando se realiza la instrucción "generar_boletas". Por lo que solo debes preocuparte de que los atributos de clases se estén actualizando cuando deban hacerlo 🤔.

Respecto al segundo punto, tienes razón que no hace mucho sentido volver a cobrar y realizar las demás instrucciones más de una vez, así que me parece sensato correr cada instrucción solo una vez :) , aunque el orden no necesariamente podría ser el entregado en el archivo de ejemplo!

Espero esto te ayude y lo deje más claro todo!!

**Comment by Jamesmoreno21** [comment]
Sii! Me quedó clarísimo, muchas gracias 😄
