### ISSUE TITLE
Error en el paso 11

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2143-2021-2/Syllabus#39]
Hola! Al ejecutar el comando rails s me aparece primero lo que sale en la primera imagen, al actualizar la pagina aparece el error de la segunda imagen.

![image](https://user-images.githubusercontent.com/65640660/131199104-bc6d80ae-7269-4ae3-84ee-deccd845b3d8.png)
![image](https://user-images.githubusercontent.com/65640660/131199144-ddf3bea4-af14-4d35-a9d7-4b77aae1acdf.png)

He buscado en google pero la verdad no entiendo nada de lo que he encontrado.

**Comment by PDominguezW** [comment]
Revisa este enlace [https://stackoverflow.com/questions/15338748/active-record-postgresql-adapter-error-in-rails](https://stackoverflow.com/questions/15338748/active-record-postgresql-adapter-error-in-rails). Avisame si te funciona alguna de las soluciones.

**Comment by arturoprietovic** [comment]
Intenté las 4 soluciones. Las últimas 2 no funcionaron. Con respecto al la primera, no pude encontrar el archivo pg_config.exe. La segunda la traté pero al instalar postgres-pr y hacer bundle install, esta no aparece en la lista, pongo bundle list y tampoco, a pesar de si estar en la carpeta gems. Trate de todo pero sigue apareciendo lo mismo :/.

**Comment by thomasrobertm** [comment]
Hola! me pasa lo mismo, intente todas las soluciones y aun asi me sigue apareciendo lo mismo. Alguna otra solucion?

**Comment by felipefuentesporras** [comment]
Cuando haces rails db:create ocurre los mimos? Te arroja algún error?

**Comment by thomasrobertm** [comment]
> Cuando haces rails db:create ocurre los mimos? Te arroja algún error?

![Captura de pantalla (63)](https://user-images.githubusercontent.com/69991915/131255640-bb1d6a2f-526d-4d9b-8343-0f69eefbb03f.png)

**Comment by felipefuentesporras** [comment]
Yap, tienes un error con el usuario de postgress y por eso no puedes crear la base de datos. Te recomendaría leer esta issue, presentan varias soluciones posibles
.
https://stackoverflow.com/questions/11919391/postgresql-error-fatal-role-username-does-not-exist

**Comment by arturoprietovic** [comment]
> Cuando haces rails db:create ocurre los mimos? Te arroja algún error?

![image](https://user-images.githubusercontent.com/65640660/131262858-fdd6d69d-3ebf-4b23-a9b8-74e2377b69e0.png)

Me dice eso, instalo pg y corro bundle install y nada. Mismo error.

**Comment by thomasrobertm** [comment]
> Yap, tienes un error con el usuario de postgress y por eso no puedes crear la base de datos. Te recomendaría leer esta issue, presentan varias soluciones posibles
> .
> https://stackoverflow.com/questions/11919391/postgresql-error-fatal-role-username-does-not-exist

Hola! Ahora me esta pasando esto :

![Captura de pantalla (64)](https://user-images.githubusercontent.com/69991915/131364755-b18ac002-7b82-4b63-9029-3969e73fb3e7.png)
