### ISSUE TITLE
Error gpg claves fallidas (paso 2)

### ISSUE THREAD

**Issue by Margarita-Paz** [IIC2143-2021-2/Syllabus#4]
Hola!
Estoy en el paso 2 y al ejecutar 
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

Me arroja gpg: recepción del servidor de claves fallida: No name

**Comment by rmastudillo** [comment]
A mi me sirvió 
gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
Lo saqué de la documentación de rvm en https://rvm.io/rvm/security
