### ISSUE TITLE
Error instalación rails -v 5.2.4 /  racc -v 1.5.2

### ISSUE THREAD

**Issue by colobos** [IIC2143-2021-2/Syllabus#40]
Hola!!
Tengo un problema al instalar rails, por si es posible una ayuda:

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.7.0 directory.

Muchas gracias de antemano!!

**Comment by josemquinta15** [comment]
Hola! por lo que comentas parece ser un problema de permisos. Prueba con
```sudo gem install rails -v 5.2.4```

**Comment by colobos** [comment]
Hola, ya lo había probado, sin embargo, me entrega el siguiente error:
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

**Comment by josemquinta15** [comment]
Podrías mandar un pantallazo del error en consola para ver que más dice? Que sistema operativo estas usando?

**Comment by colobos** [comment]
Adjunto pantallazo de ambos errores. Respecto al sistema operativo, estoy utilizando una maquina virtual (VirtualBox) con Ubuntu 20.04.3 LTS.
![1](https://user-images.githubusercontent.com/80869347/131239210-517fe83d-291c-4b27-992e-b14bc6cc82b0.PNG)
![2](https://user-images.githubusercontent.com/80869347/131239212-eea7d3df-af14-4ddb-b9ad-86abb295d026.PNG)

**Comment by josemquinta15** [comment]
Probaste instalando ```ruby-dev``` o ```ruby-devel```, que es lo que recomienda el error? si es que no te recomiendo instalarlos y probar... [acá](https://stackoverflow.com/questions/13767725/unable-to-install-gem-failed-to-build-gem-native-extension-cannot-load-such) hay un link con los pasos

**Comment by colobos** [comment]
Funciono perfecto!!, muchísimas gracias!!
