### ISSUE TITLE
Archivos Output

### ISSUE THREAD

**Issue by ian-fell** [IIC2143-2021-2/Syllabus#41]
Hola! 
Tengo una duda respecto a los archivos que debemos generar. Nos indica el enunciado que debemos crear 4 funciones que escriban sobre un archivo. Mi duda es, es un único archivo el que debemos crear y escribir todo en él? O puedo crear un archivo distinto para cada función? Con esto me refiero, puedo crear un archivo para la info de las mesas, otro para las boletas, otro para top mesas y así?

**Comment by JosefaPaz** [comment]
Hola! 

Sería un único archivo, donde a partir de cada instrucción se escribe la información, por ejemplo, si el archivo de instrucciones fuera:

**instrucciones.txt:**
```
informacion_mesas
generar_boletas
top_mesas
top_meseros
```

el formato del output debería ser:

**output.txt:**
```
COMIENZA INFORMACION MESAS
{id mesa 1} {nombre mesero mesa 1} {nombre cliente 1} {nombre cliente 2} {nombre cliente 3}
{id mesa 2} {nombre mesero mesa 2} {nombre cliente 4} {nombre cliente 5} {nombre cliente 6}
.
.
.
{id mesa n} {nombre mesero mesa n} {nombre cliente m-2} {nombre cliente m-1} {nombre cliente m}
TERMINA INFORMACION MESAS
COMIENZA GENERAR BOLETAS
{id mesa 1} {nombre cliente 1} {total cliente 1} {nombre cliente 2} {total cliente 2} {nombre cliente 3} {total cliente 3} {total mesa 1}
{id mesa 2} {nombre cliente 4} {total cliente 4} {nombre cliente 5} {total cliente 5} {nombre cliente 6} {total cliente 6} {total mesa 2} 
.
.
.
{id mesa n} {nombre cliente m-2} {total cliente m-2} {nombre cliente m-1} {total cliente m-1} {nombre cliente m} {total cliente m} {total mesa n}
TERMINA GENERAR BOLETAS
COMIENZA TOP MESAS
{id mesa 1} {total mesa 1}
{id mesa 2} {total mesa 2}
{id mesa 3} {total mesa 3}
TERMINA TOP MESAS
COMIENZA TOP MESEROS
{id mesero 1} {propina mesero 1}
{id mesero 2} {propina mesero 2}
{id mesero 3} {propina mesero 3}
TERMINA TOP MESEROS
```

Espero esto lo aclare, de igual manera durante el día subiré un output de ejemplo con los datos del csv :)
