### ISSUE TITLE
Problema manejo de archivo Tarea

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2143-2021-2/Syllabus#43]
Hola tengo un problema, de acuerdo a lo que entendi el primer argumento recibido dentro de la consola sera la carpeta data, donde adentro tendra los archivos .csv, ahora hice un variable la cual sera esa carpeta, algo del estilo: carpeta = ARGV[0] , pero ahora aquí va mi problema, como logro manipular esta carpeta? , es decir, como la utilizo para ponerla en la ruta de la variable que utilizare para abrir los csv, algo así csv_clientes = CSV.read ( carpeta/"clientes.csv") , no entiendo como pone la variable carpeta dentro de la ruta, espero que se me haya entendido:(

**Comment by chineseJack564** [comment]
Como los archivos dentro de la carpeta son constantes, una forma es realizar concatenación de string (formando la ruta completa de cada archivo csv) con la ruta de carpeta que recibiste de input con cada uno de los csv.
Puedes probar con el siguiente codigo:


`if File.exist?("ruta/al/archivo")`
  código si el archivo o la carpeta existe

`else`

  código si el archivo o la carpeta no existe

`end`
