### ISSUE TITLE
[Tarea] Duda total mesa

### ISSUE THREAD

**Issue by crow-rojas** [IIC2143-2021-2/Syllabus#44]
Hola! Tengo una duda respecto al total de la mesa. Este total se considera con el 10% de la propina o solo con el valor neto de los platillos?

gracias!

**Comment by sebastianbreguel** [comment]
Hola! como sale en el enunciado en la sección 5 y 6:
!
[imagen](https://user-images.githubusercontent.com/62109266/131393909-32528f7a-46f9-4b71-8226-02cb836ec405.png)

El total de la mesa se calcula con la suma de cada cliente, donde el total del cliente se calcula con su plato+10%. Por lo que en el total de la mesa ya vendria considerado la propia.
