### ISSUE TITLE
[Tarea] - Duda top_mesas

### ISSUE THREAD

**Issue by ShescBlank** [IIC2143-2021-2/Syllabus#47]
Hola :D Si no estoy entendiendo mal, el método generar_boletas es el encargado de hacer el "cobro" a los clientes, es decir, en este se revisa si el cliente puede comprar lo que pidió y restarle a su dinero de ser necesario, además de agregar la propina correspondiente. Entonces mi duda es ¿qué pasa si es que llamo a top_mesas antes de generar_boletas? Pienso que como todavía no se ha hecho el cobro, entonces ninguna mesa ha gastado dinero, lo que significa que no habría un verdadero top. También podría hacer un estimado de lo que va a gastar cada mesa y hacer el top respecto a eso, sin modificar todavía el dinero de los clientes y las propinas. O simplemente aplicar el cobro como lo haría generar_boletas (y preocuparme de no repetir las mismas acciones si es que se llama a este método después).

Muchas gracias :D

**Comment by JosefaPaz** [comment]
Hola!!

Tienes razón, para no tener problemas en el modelamiento me parece la opción de hacer "un estimado de lo que va a gastar cada mesa y hacer el top respecto a eso, sin modificar todavía el dinero de los clientes y las propinas." De todas formas, me voy a preocupar al revisar de que no existan incongruencias con las instrucciones para no perjudicarlos.

Ojalá esto te ayude!!
