### ISSUE TITLE
Invitación repositorio proyecto

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2143-2021-2/Syllabus#48]
Hola! ¿Dónde me debería haber llegado la invitación al repositorio del proyecto? Estoy en mi usuario de git hub pero no me aparece nada.

**Comment by felipefuentesporras** [comment]
Hola, debería haberte llegado un mail con la información. Si no te llego, envíale un correo a Moisés (coordinador proyecto) con tu situación y tu usuario.
