### ISSUE TITLE
Problema con rails db: create

### ISSUE THREAD

**Issue by jesusotov** [IIC2143-2021-2/Syllabus#49]
![error](https://user-images.githubusercontent.com/80776134/131273423-82e3cb04-32ce-40a7-8c3a-69bf631daae8.PNG)

Hola! Al crear la base de datos me aparece este error, que puedo hacer al respecto?

**Comment by domingo2000** [comment]
Hola, creaste el usuario de postgres con el nombre de tu sistema y le diste `SUPERUSER`?? (paso 7 en la guía de ubuntu)

**Comment by jesusotov** [comment]
Ahí me funcionó! Muchas gracias!!
