### ISSUE TITLE
Ruby on rails

### ISSUE THREAD

**Issue by Cadutodalcielo** [IIC2143-2021-2/Syllabus#5]
Hola 
por lo que entendi según la guia es necesario instalar wsl para instalar ruby on rails en windows, el problema es que cuando activo wls me crashea windows, puedeo instalar directamente en windows o me afectara en el futuro del proyecto?

Gracias

**Comment by domingo2000** [comment]
Hola, como intentaste instalar wsl, con la instalación manual o con windows insider??

**Comment by Cadutodalcielo** [comment]
> Hola, como intentaste instalar wsl, con la instalación manual o con windows insider??

Manual, segui este tutorial 
https://www.windowscentral.com/how-install-wsl2-windows-10

**Comment by domingo2000** [comment]
Vi el tutorial y tiene los mimsos comandos que el de la página de microsoft, ¿Y corriste `wsl --install`? ¿o corriste todos los otros comandos para hacer la instalación manualmente ?

**Comment by Cadutodalcielo** [comment]
puse este comando "dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart" despues reinicié y me dio pantallazo azul

**Comment by domingo2000** [comment]
y que error te salía en la bluescreen?

**Comment by Cadutodalcielo** [comment]
![image](https://user-images.githubusercontent.com/62030238/130338280-b8ffa21f-4ed6-42e1-a2a6-543b57d4329d.png)

**Comment by domingo2000** [comment]
Solo para descartar, Tienes activada la virtualizacion en tu bios??

**Comment by Cadutodalcielo** [comment]
> Solo para descartar, Tienes activada la virtualizacion en tu bios??

si

**Comment by Pablok98** [comment]
@Cadutodalcielo Pudiste arreglar el problema?

**Comment by Cadutodalcielo** [comment]
> @Cadutodalcielo Pudiste arreglar el problema?

si, lo hice con el método insider y no manual
