### ISSUE TITLE
Pregunta Tarea apartado 5

### ISSUE THREAD

**Issue by fernandolalanne** [IIC2143-2021-2/Syllabus#50]
Hola! Quería preguntar si el apartado 5, 6 y 7 también deben ser funciones creadas al igual que en el apartado 4. En este mismo sentido quería preguntar si existe alguna restricción en cuanto a la cantidad de argumentos que se le pueden dar a los métodos. Gracias!

**Comment by JosefaPaz** [comment]
Hola!!

No es necesario que sean funciones, estos apartados puedes modelarlos como más quieras 😄, por lo que no existe tampoco una restricción de cuántos argumentos puedes darles.

Éxito!!

**Comment by fernandolalanne** [comment]
Vale muchas gracias! Y a los métodos del ejercicio 4 le puedo agregar los argumentos que yo quiera?

**Comment by JosefaPaz** [comment]
@fernandolalanne Sii, ningún problema :)
