### ISSUE TITLE
[Tarea] - Generar cobro

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2143-2021-2/Syllabus#51]
En la mismalinea que la issue #47, **se debe generar un cobro al cliente en alguna funcion?** esto ya que en la correccion del enunciado, en la seccion de aclaraciones da la idea de que si, pero en la seccion de los metodos nunca se menciona que se debe generar un cobro

**Comment by JosefaPaz** [comment]
Hola!

No es necesario como tal generarle un cobro al cliente en alguna función, pero sí es recomendable para que puedas ir guardando la información de lo que va pasando en algún atributo. Quizá con la respuesta de la issue #47 te quede más claro esto!

Saludos :)

**Comment by Lord-Kelsier** [comment]
Gracias
