### ISSUE TITLE
[Tarea] top_meseros()

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2143-2021-2/Syllabus#52]
Hola. Tengo una confusión acerca de la sección 7 'Calcular propina' . Existen dos valores distintos de la propina que se le asigna a un mesero
1. El atributo 'propina' de la clase Mesero, el cual viene asignado en el archivo meseros.txt
2. El 10% del total gastado en cada mesa que atiende

¿Cual de los dos valores deberíamos usar para el método?

**Comment by JosefaPaz** [comment]
Hola!!

El atributo propina que se encuentra en el archivo `meseros.txt` sería la propina que tiene el mesero en el inicio del turno. Para calcular la propina, se debe sacar el 10% del total de la mesa que atiende y esto sumarselo al atributo propina. Para el método calcular propina, como estarías calculando la propina solo de una mesa o un cliente, te serviría lo segundo, pero no olvides luego sumarselo al mesero para ir actualizando la info :)

Saludos!!
