### ISSUE TITLE
[Tarea Ruby] Buzón de entrega Tarea Ruby

### ISSUE THREAD

**Issue by raimundomartinez** [IIC2143-2021-2/Syllabus#53]
Hola! Quería saber si van a habilitar el buzón de entrega de la tarea de ruby. En el enunciado salía que se tenía que entregar en un buzón de tarea de Canvas, ¿Sigue este siendo el caso? De ser así, ¿cuando habilitaran este buzón?

**Comment by JosefaPaz** [comment]
Hola!

Ya está habilitado, disculpa la demora!

Saludos :)
