### ISSUE TITLE
Problemas con la instalacion de RVM

### ISSUE THREAD

**Issue by Franco1208** [IIC2143-2021-2/Syllabus#55]
Hola! 
Estoy siguiendo la guía de setup para windows, pero he tenido problemas con la instalación de rvm y por lo tanto no puedo instalar rails. Podrían ayudarme por favor? 🚀 

Adjunto captura de pantalla
![porsiaca](https://user-images.githubusercontent.com/69912991/131424644-8ca8721b-4d05-4a6b-8cad-8770eb748a7a.jpg)

Gracias!

**Comment by PDominguezW** [comment]
Recuerda que debes reiniciar la consola de ubuntu antes de ejecutar el comando `rvm -v`
