### ISSUE TITLE
Warning al correr rails db:create

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2143-2021-2/Syllabus#56]
Me funcionó todo, pero me aparece esto. Va a generar un problema más adelante? si es que sí, cómo lo arreglo?
![image](https://user-images.githubusercontent.com/65640660/131428282-047c4026-7320-47ee-bae5-3683cb6a45a5.png)

**Comment by festelle** [comment]
Hola! En mi experiencia, esos errores no generan problemas (siempre me han salido esas advertencias y he podido trabajar sin problemas).
