### ISSUE TITLE
[Tarea] - Pregunta apartados 5, 6 y 7

### ISSUE THREAD

**Issue by RafaelEdwards** [IIC2143-2021-2/Syllabus#57]
Hola!

En el enunciado dice que la propina se debe calcular respecto al número total de platillos, es decir, luego de obtener la suma de los costos de todos los platos que se consumieron. Sin embargo, si se hace esto el cliente podría no tener el dinero suficiente para pagar la propina a la hora de calcular el gasto total. 

¿Podríamos calcular el costo total y la propina de cada plato por separado y así ir viendo si el cliente puede recibir más platos de  tal manera en que no se quede sin dinero para pagar la propina?  

**La propina calculada respecto al costo de los platos sumados no es igual a la que se obtiene al sacar la de cada plato por separado y luego sumarla, debido a que se nos pide redondear por exceso.

Muchas gracias!

**Comment by JosefaPaz** [comment]
Hello!

Tienes toda la razón! Ningún problema si calculan la propina y los platillos como lo indicas :) Me preocuparé también de añadirlo en el enunciado para que no tengan complicaciones.

Éxito!!
