### ISSUE TITLE
duda Metodo top_meseros()

### ISSUE THREAD

**Issue by LucaSpiniello** [IIC2143-2021-2/Syllabus#58]
En el metodo top_meseros() con propina se refieren solo a la inicial o a esta mas la que cada mesero se gana por sus pedidos?? Porque en el expected_output simpemente pusieron la inicial....

**Comment by JosefaPaz** [comment]
Hola!

Es la inicial + la que cada mesero gana con sus pedidos. Actualizaré hoy el expected_output con la información correcta. Gracias por el aviso! 

Éxito! :)
