### ISSUE TITLE
Paso 1  "sudo apt-get update"

### ISSUE THREAD

**Issue by Piolawa** [IIC2143-2021-2/Syllabus#6]
Hola!, cada vez que pongo `sudo apt-get update` en la consola de ubuntu (tengo la partición del disco), me sale el siguiente error:

```
(base) paula@paula-HP-240-G6-Notebook-PC:~$ sudo apt-get update
[sudo] contraseña para paula: 
Lo sentimos, vuelva a intentarlo.
[sudo] contraseña para paula: 
Ign:1 http://archive.ubuntu.com/ubuntu cosmic InRelease
Err:2 http://archive.ubuntu.com/ubuntu cosmic Release
  404  Not Found [IP: 91.189.88.142 80]
Leyendo lista de paquetes... Hecho
E: El repositorio «http://archive.ubuntu.com/ubuntu cosmic Release» no tiene un fichero de Publicación.
N: No se puede actualizar de un repositorio como este de forma segura y por tanto está deshabilitado por omisión.
N: Vea la página de manual apt-secure(8) para los detalles sobre la creación de repositorios y la configuración de usuarios.
```

He intentado todo lo que pillé en internet, lo último que ocupé fue lo de este link: https://www.tutorialesubuntu.com/2020/08/01/solucionar-errores-apt-get-update-y-restaurar-repositorios/

**Comment by nicolecll** [comment]
Hola! Al buscar un poco sobre tu error me parece que puede deberse a que hay una mezcla de versiones de los repositorios que intentas actualizar, en este caso que es un poco complejo te recomiendo buscar que version de Ubuntu tienes y borrar todos aquellos paquetes que no pertenezcan a esa versión, mas info acá  -> [https://foro.vozidea.com/d/253-error-no-se-puede-actualizar-de-un-repositorio-como-este-de-forma-segura/6](url)

Otro problema que puede ser y que es mas sencillo es que se están corriendo dos procesos idénticos a la vez en tu PC y uno bloquea al otro, para esto basta con reiniciar el sistema operativo (aunque suene easy). 

Espero te sea de ayuda y cuéntame si te funciona!
