### ISSUE TITLE
Duda orden clientes

### ISSUE THREAD

**Issue by crow-rojas** [IIC2143-2021-2/Syllabus#60]
Hola! Se me generó una duda con el método informacion_mesas. Yo hasta ahora estaba mostrando los clientes de cada mesa por orden de su id, de menor a mayor, pero en el archivo output que subieron no parece seguir ese mismo orden. En el enunciado solo se especifica que las mesas se ordenan de menor a mayor segun el id (de la mesa), pero no como colocar los clientes. Me lo podrían aclarar?

gracias!

**Comment by JosefaPaz** [comment]
Hola!!

Se ordenarán por orden alfabético los clientes. Lo añadiré para evitar confusiones.

Gracias por el comentario! :)
