### ISSUE TITLE
[Tarea 0] - General

### ISSUE THREAD

**Issue by dsepulveda3** [IIC2143-2021-2/Syllabus#61]
Tengo varias dudas generales. Por lo que me di cuenta, la tarea 0 **NO** se sube al repositorio personal, sino que en un archivo zip en canva. **Mi primera pregunta es la siguiente:**
La tarea dice que el repo (si hubiese), deberia tener este formato
![image](https://user-images.githubusercontent.com/62180259/131567990-b860cc0e-a07f-4a93-a28c-369ea28cc7b9.png)

¿Esto significa que dentro del archivo zip debe haber una carpeta que se llame repo con la carpeta data, archivo instr y main?

**Mi segunda pregunta** es cómo se corre el código de Ruby. Abro VS code y después lo corro desde Ubuntu (tengo Windows), o simplemente corriéndolo desde VS code funciona.

**Comment by Lord-Kelsier** [comment]
Primero, no soy ayudante, pero yo entiendo que no es necesario crear esas carpetas ya que a `File.open` le das un path relativo en el cual se encuentra el archivo ``instr.txt`` y la carpeta data, estos pueden tener cualquier nombre, pues los recibirás como input al ejecutar `main.rb`, el cual se ejecuta maediante la consola, da igul que consola mientras este ubicada en la carpeta donde este main.rb.

**Comment by chineseJack564** [comment]
Hola, respecto a la primera prgunta, en el archivo zip solo se sube los archivos .rb, y en tu main debes recibir y leer los inputs como se menciona en el enunciado. (recibiendo sus path como argumentos)

Para la segunda pregunda, puedes correr el codigo en ubuntu realizando cd o usar el extensión remote wsl de vscode.

**Comment by dsepulveda3** [comment]
Gracias ! Me queda clarísimo el segundo punto.}

El primero me complica, no estoy entendiendo como recibir y leer los inputs leyendo el enunciado :/

**Comment by dsepulveda3** [comment]
Me confunde que como tratar el código para que el ayudante a la hora de correrlo pueda hacer esto y le funcione

![image](https://user-images.githubusercontent.com/62180259/131748773-056a178b-d381-4185-bab7-cb67757802e1.png)

**Comment by Lord-Kelsier** [comment]
`ruby main.rb` lo que hace es ejecutar el script `main.rb`, un script puede recibir parametros los cuales se deben separar por espacios. En este caso son 3 parametros `data`, `instr.txt`, `output.txt`, estos parametros son accesibles desde tu script, quedando almacenados en el array `ARGV`. Entonces puedes hacer lo siguiente:

```rb
segundo_parametro = ARGV[1] #=> "instr.txt"

```

**Comment by dsepulveda3** [comment]
Dale. A ver si estoy entendiendo. Lo que debo hacer es meter lo que está en el archivo instuccions.txt dentro de un argv para luego leer cada posición del argv y correr cada función pedida ?

Sorry pero ando tremendamente confundido en como se piden manejar los datos. Me confundi porque hay que ocupar un ARGV.

**Comment by JosefaPaz** [comment]
@dsepulveda3  Claro! Eso mismo es lo que hay que hacer, quizá con lo visto en la ayudantía de Ruby te pueda aclarar un poco el uso de ARGV, si no, nos sigues comentando mediante issues :)

Éxito!
