### ISSUE TITLE
[Proyecto] - Conectar Heroku con repositorio

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2143-2021-2/Syllabus#62]
Hola, estoy intentando conectar el repositorio con Heroku pero como el repositorio no es mío no aparece. 
![heroku](https://user-images.githubusercontent.com/69614275/131581628-411b9e1d-6b9a-460b-8ca9-c08742533523.png)

**Comment by domingo2000** [comment]
Las repos del curso no permiten conexión automatica cin github para hacer los deploys, por lo tanto debes hacerlo con la herramienta heroku git, descargando el heroku CLI en tu computador y siguiendo esos pasos. Cualquier duda (ademas de la issue que obvio puedes seguir preguntando) vamos a tener ayudantia de git + heroku este viernes y ahí se mostrará como hacer el deploy en heroku.

**Comment by Lord-Kelsier** [comment]
Muchas gracias
