### ISSUE TITLE
[Setup] Error al entrar a localhost

### ISSUE THREAD

**Issue by rbmeza** [IIC2143-2021-2/Syllabus#63]
Hola! adjunto el error que me entrega al apretar el link de localhost
![error](https://user-images.githubusercontent.com/48302258/131589681-2cf6442a-8807-4f07-bc72-c6dd00b841a8.PNG)

**Comment by domingo2000** [comment]
Dos preguntas
1. Pudiste abrir el "you are on rails" anteriormente y ahora no puedes abrirlo? O nunca te ha funcionado
2. Iniciaste el servicio de postgresql al encender tu computador? Es decir corriste `sudo service postgresql start` en tu consola de ubuntu antes de correr `rails s`??

**Comment by rbmeza** [comment]
Nunca me ha salido "you are on rails" y recién hice lo de 2. y cambio el error a este:

![error](https://user-images.githubusercontent.com/48302258/131591608-9d202a0b-58d6-4386-a54a-e2b365849efd.PNG)

**Comment by chineseJack564** [comment]
Tienes que hacer:
`rails db:create`

**Comment by domingo2000** [comment]
Suponiendo que lo que te dijeron arriba funciona te explico un poco lo que pasa y porque tienes dichos errores:
1. Al generar un proyecto nuevo en rails este necesita generar una base de datos, para eso corremos `rails db:create`, y dicho comando crea una base de datos postgresql por nosotros para la app.
2. Obviamente para que se cree la base de datos con el comando anterior debes tener postgresql "encendido", lo mismo si quieres correr tu aplicación. Por esto cada vez que reinicies tu computador debes correr `sudo service postgresql start` así postgresql se "prende" (por eso el service start), tanto para hacer una base de datos nueva (ejemplo un proyecto nuevo y su creación de base de datos como en el paso 1. O para que funcionen tus proyectos que estan ya usando una base de datos ya creada.

**Comment by rbmeza** [comment]
Ahí funcionó!! gracias por tanto<3
