### ISSUE TITLE
Aclaración sobre generar_boletas

### ISSUE THREAD

**Issue by ian-fell** [IIC2143-2021-2/Syllabus#64]
Hola! 
Creando la función generar_boletas me surgió la duda si debo imprimir todas las mesas, aun asi no tengan clientes, o solo debo imprimir las que tengas clientes? Esto lo observé porque no siempre hay mesas con clientes, por lo que quedan lineas en el archivo de output solo con el id de la mesa y nada más, pero en el enunciado nos pide imprimir todas las mesas, sin nombrar excepciones.

**Comment by chineseJack564** [comment]
Como los archivos dentro de la carpeta son constantes, una forma es realizar concatenación de string (formando la ruta completa de cada archivo csv) con la ruta de carpeta que recibiste de input con cada uno de los csv.
Puedes probar con el siguiente codigo:
`if File.exist?("ruta/al/archivo")
  # código si el archivo o la carpeta existe
else
  # código si el archivo o la carpeta no existe
end`
