### ISSUE TITLE
[Tarea 0] Duda Top Mesas

### ISSUE THREAD

**Issue by JuanpaBC** [IIC2143-2021-2/Syllabus#65]
Hola, si el total mesa de dos mesas distintas resultó igual, y al mismo tiempo ese valor es el tercero más grande de todas las mesas, en el top mesas imprimo las 4 mesas (imprimo todas las mesas con los 3 gastos más altos) o se hace algo distinto?

Desde ya gracias.

**Comment by JosefaPaz** [comment]
Hola!!

Si llegara a ocurrir ese caso, como las mesas se ordenan por id de menor a mayor, se imprime la mesa con el menor id :)

Saludos!!

**Comment by JuanpaBC** [comment]
gracias!

**Comment by JuanpaBC** [comment]
disculpa, otra duda, es que endenantes no cache que el orden de impresión era ascendente según el id de la mesa, qué debo hacer en el caso en el que dos mesas acabaron con el mismo gasto, ese gasto esta dentro de los 3 gastos mayores, pero el id de ambas mesas es menor que el id de una de las mesas con gasto distinto pero dentro de los top 3 gastos, de manera que si priorizo la impresión segun id de mesa y quiero imprimir 3 mesas, se imprimirían dos mesas con el mismo gasto, al mismo tiempo que la una de las mesas con gasto dentro del top 3 no sería impresa. En tal caso sería mejor imprimir las 4 mesas nomás? o dejo que ocurra lo que describo?

Mil disculpas si mi consulta resulta muy confusa. Desde ya gracias.
