### ISSUE TITLE
Borrar base de datos con caracteres especiales

### ISSUE THREAD

**Issue by cristobal-larach** [IIC2143-2021-2/Syllabus#66]
Hola! En un principio cree las bases de datos como "<nombre proyecto>_development" y "<nombre proyecto>_test" sin reemplazar el nombre del proyecto. Al darme cuenta, procedí a crearlas bien. Ahora quiero borrar las dos primeras bases de datos, pero al correr "drop database <nombre proyecto>_development;" me lanza un syntax error cerca de <. Intenté con comillas simples, doblas, backtick, y sin nada. Ninguna dio resultado. ¿Alguna idea de como eliminarlas?

También trate de entrar en esa base de datos y luego cambiar el nombre de la  misma usando "alter database :DBNAME rename ... ", pero tampoco funcionó.

**Comment by chineseJack564** [comment]
Hola
En rails tu creas tus bases de datos con comando `rails db:create`, y los nombres de los bases de datos se crean automatico. Y para borrarlos debes hacer `rails db:drop`
saludos
