### ISSUE TITLE
[Tarea] - Preguntas generales

### ISSUE THREAD

**Issue by ShescBlank** [IIC2143-2021-2/Syllabus#67]
Hola :D Estaba leyendo el output que se subió y me surgieron varias dudas, muchas relacionadas con otras issues que también se preguntaron.

1) En informacion_mesas y generar_boletas, los nombres de los clientes están ordenados por orden alfabético y no por sus ids, esto debe ser así?
2) si una mesa no tiene clientes, se debe saltar en el output?
3) No debemos modificar los atributos propina y dinero de los meseros y clientes? Esta pregunta me surge porque las propinas del output en top_meseros son las mismas iniciales.
4) No entiendo muy bien el cálculo de las boletas en el output, por ejemplo:
Ignacio es el cliente de id 6 y pidió los platillos de id 17, 7 y 2, los que tienen precios 4949, 10565 y 1101, que suman 16615 y si añadimos el 10% de este obtenemos 18276.5 (que redondeado por exceso es 18277). Pero en el output subido aparece 20324.
5) Por último, no se escribe nada del método top_mesas.

No sé si estaré entendiendo algo mal y perdón por hacer tantas preguntas, pero creo que son importantes y también considero que responden a otras issues anteriores.

Muchas gracias y espero estén teniendo una buena semana :D

**Comment by JosefaPaz** [comment]
Hola!!

Te respondo por puntos:

1- Sí, se subordenan por orden alfabético los clientes. Lo añadiré para que todos lo tengan claro!
2 - Yes, se debe saltar el output como se comentó en la issue #64 
3 - Esto fue un error de código, así que sí deben modificarlo. Lo actualizaré durante el día para que tengan la información correcta!
4 - Voy a revisar esto durante el día y te confirmo la información volviendo a escribir en esta issue! 
5 - Totalmente, no se grabó la información. También lo subiré actualizado :)

Y nooo, no te disculpes por las preguntas, es más, gracias por todas las preguntas, nos sirven para ayudarlos y tener en cuenta a la hora de corregir :)

Estamos hablando!

**Comment by JosefaPaz** [comment]
@ShescBlank Hello! ya se encuentra actualizado el archivo de output con los cambios. Gracias! :)

**Comment by ShescBlank** [comment]
Gracias :D
