### ISSUE TITLE
Error paso 8:  rails new <nombre proyecto> --database=postgresql

### ISSUE THREAD

**Issue by Franco1208** [IIC2143-2021-2/Syllabus#68]
Hola! Al escribir este codigo me tira un error y no entiendo como solucionarlo. 
Esto es lo que me sale al ejecutarlo
![error ](https://user-images.githubusercontent.com/69912991/131731893-b9b947f4-e7f2-46f2-a05a-2b32317d03e1.jpg)

Quedo atento!

**Comment by domingo2000** [comment]
Hola, creo que tu problema se debe a que en la terminar estás "parado" en el directorio de System32 en vez de en el root de WSL, para llegar al root de WSL abre una terminal normal de windows y escribe `wsl`, deberías quedar en algo asi 
![image](https://user-images.githubusercontent.com/40220174/131915946-9f641c61-76c3-4ec3-a160-49d5bccaff04.png)


A veces al ejecutar wsl tampoco se para en el directorio correcto, para eso solo debes moverte usando `cd ..` para ir hacia atras y `cd <directorio>` para ir hacia adelante. Te envio un pantallazo de como me meuvo yo para llegar al root de mi wsl (`ls` sirve para ver que hay en el directoria actual, algo asi como `dir` de windows) 
![image](https://user-images.githubusercontent.com/40220174/131916143-a331c8fd-0298-43d5-8f35-4228a3a0f67a.png)
Quedo atento a como te va

PD: Yo en general abro wsl en windows escribiendo Ubuntu en el buscador de la siguiente forma 
![image](https://user-images.githubusercontent.com/40220174/131916230-22c9e3bc-932d-4d0e-8d93-e992403cd43d.png)
y eso me deja justo en el root de Ubuntu quedando asi:
![image](https://user-images.githubusercontent.com/40220174/131916292-d2fea73a-2985-41fb-bcd9-f1ce27c0cefe.png)

**Comment by Franco1208** [comment]
Hola muchas gracias por tu respuesta!! Lo que no se es en que directorio me tengo que parar ahora para ejecutar el codigo, porque me sigue tirando el mismo erro:/
