### ISSUE TITLE
Error setup parte 4 Mac

### ISSUE THREAD

**Issue by robertoorrego** [IIC2143-2021-2/Syllabus#69]
Hola, estaba instalando Ruby y me tira un error en la linea para instalar rails.
<img width="914" alt="Captura de Pantalla 2021-09-01 a la(s) 4 36 05 p  m" src="https://user-images.githubusercontent.com/70174581/131742681-12a28152-5ba0-409a-9227-aa7f1d805388.png">

**Comment by borquezmartin** [comment]
Holaa, tengo el mismo erro que el compañero
