### ISSUE TITLE
[Ubuntu] Paso 9-carpeta config

### ISSUE THREAD

**Issue by Lord-Kelsier** [IIC2143-2021-2/Syllabus#7]
Hola, en el paso 9 dice que debo ingresar a la carpeta config dentro del proyecto, pero esta no se ha creado. Puedo crearla y añadir el archivo o esa carpeta debia contener otras cosas que no tengo?

![Screenshot from 2021-08-21 20-59-29](https://user-images.githubusercontent.com/69614275/130338640-5acc9ff1-f19b-440f-b1d1-3baf7b36072e.png)

**Comment by nicolecll** [comment]
Hola! Al ver la imagen que adjuntas, pareciera ser que tu app no se creo bien, ya que esta automáticamente contiene todas las carpetas que necesitarás. 

Para que te hagas una idea, se debería crear un proyecto que tenga las siguientes carpetas. 
![Captura de pantalla (446)](https://user-images.githubusercontent.com/69603557/130338869-c1f002ce-a786-4e9b-9a9e-e837c43f6beb.png)

**Comment by Lord-Kelsier** [comment]
Ya encontre la solucion por si alguien mas le paso. Dado que acababa de instalar Ubunto no habia instalado git, el comando: `rails new <nombre proyecto> --database=postgresql` necesita que este git instalado para crear esas carpetas
