### ISSUE TITLE
Error setup parte 5 Mac

### ISSUE THREAD

**Issue by PaulaCoronado** [IIC2143-2021-2/Syllabus#70]
Hola! Tengo un error en el paso 5, en la ayudantía lo intentamos resolver, pero no resultó :( , Qué puede ser ?
![Captura de Pantalla 2021-09-01 a la(s) 19 04 54](https://user-images.githubusercontent.com/42159693/131756858-bbb00659-47d8-4366-a7cd-3af3d2982ba0.png)

**Comment by nataliasuarez99** [comment]
Hola!! tengo el mismo error, lo pudiste arreglar??
