### ISSUE TITLE
[Tarea] - Orden de nombres en informacion_mesas()

### ISSUE THREAD

**Issue by sebadht** [IIC2143-2021-2/Syllabus#71]
Hola! al escribir la informacion del metodo informacion_mesas() en el output.txt importa el orden en el que se escriben los nombres de los clientes? 

Por ejemplo si el output esperado es:

10 Constanza Ortiz Alexander Hernan Raimundo

y mi programa escribe:

10 Constanza Ortiz Hernan Raimundo Alexander

Esto se consideraría bueno o malo?

[edit] 

Otra duda, cuando las mesas no tienen clientes las escribimos en el output o no se incluyen?

Muchas gracias de antemano!

**Comment by JosefaPaz** [comment]
Hola!!

Espero que estés bien, en las issues #64 y #67 se responden esas dudas!

Éxito!!

**Comment by sebadht** [comment]
Lei las issues antes y no había encontrado esas, mala mía xd muchas gracias! Saludos!!
