### ISSUE TITLE
[TAREA 1] Consideraciones Importantes

### ISSUE THREAD

**Issue by JosefaPaz** [IIC2143-2021-2/Syllabus#72]
Hello!

Creí mejor pinnear en esta issue las consideraciones importantes que han mencionado en las issues, para que todas las tengan claras:

1. En informacion_mesas y generar_boletas los nombres de los clientes se ordenan mediante orden alfabético.
2. Si una mesa no tiene clientes, no se debe imprimir la mesa.
3. En el método top_meseros al indicar la propina es la propina inicial en el txt más la que cada mesero gana por los pedidos.
4.  Pueden calcular el costo total y la propina de cada plato por separado y así ir viendo si el cliente puede recibir más platos de tal manera en que no se quede sin dinero para pagar la propina.

Además, ya se encuentra arriba el output modificado, ya que le faltaba el método de top_mesas y los valores de top meseros estaban incorrectos 👀 .

Desde ya disculpen las diferencias, espero que estos cambios les ayuden con su evaluación!! :)

**Comment by sperezmasri** [comment]
Hola @JosefaPaz, me parece que hay un error con el _top mesas_, ya que las sumas no cuadran con la información de _generar boletas_. Y me queda otra duda, que en el enunciado, si no me equivoco, en _generar boletas_ sale que al final se imprime el total de la mesa pero esto creo que no se imprimió en el caso del archivo output de ejemplo. Gracias de antemano, saludos 😁

**Comment by JosefaPaz** [comment]
@sperezmasri Hola! Para estas dudas mejor hacer una nueva issue :) En todo caso, te respondo aquii

- Modificado nuevamente las sumas, disculpa tanta confusión 😵 
- Efectivamente, lo agregué para seguir el orden del enunciado.

Gracias por las correcciones! :)
