### ISSUE TITLE
Pedidos

### ISSUE THREAD

**Issue by Arturovidalr** [IIC2143-2021-2/Syllabus#76]
Hola! tengo una duda:
Para entregar los platos, ¿los voy entregando por pedido o por platillo? Es decir, ¿entrego primero el pedido 1 entero, luego el 2, y así, o, por otro lado, el platillo 1 a las mesas que los pidieron, luego el platillo 2, etc.?

**Comment by JosefaPaz** [comment]
Hola!

Excelente pregunta, lo mejor sería hacerlo por pedido! Ya que así entregas a toda la mesa, y luego si esa misma mesa pide, puedes revisar si el cliente X tiene el dinero suficiente para comprarlo.

Éxito!!
