### ISSUE TITLE
[Tarea] - Duda expected output

### ISSUE THREAD

**Issue by pabloalvarez67** [IIC2143-2021-2/Syllabus#77]
Hola, bajo que criterio de orden debiesen de ser mostrados los clientes en las respectivas mesas?
Los estaba ordenando por su id de cliente, pero no me quedan todas las lineas igual al menos en las funciones que ya he programado.

Gracias de antemano!

**Comment by JosefaPaz** [comment]
Hola! 

Tal como sale en la issue #72 deben ser de acuerdo a orden alfabético :)
