### ISSUE TITLE
Terminal de ubuntu

### ISSUE THREAD

**Issue by iankreisberguc** [IIC2143-2021-2/Syllabus#78]
Hola, tengo un problema con la terminal de ubuntu, no puedo pegar ni con ctr +v, ni con boton derecho, no con shift + insertar, he buscado en internet pero no logro encontrar el problema.
PD: aclaración: todo me funciona bien en ubuntu solo no puedo pegar en la consola

**Comment by PDominguezW** [comment]
Quizas alguna de las soluciones de [](https://askubuntu.com/questions/961175/copy-and-paste-doesnt-work-in-the-terminal) te pueda servir.

**Comment by iankreisberguc** [comment]
ninguna de esas soluciones me ha funcionado
