### ISSUE TITLE
[Tarea 0] Solo hay un mesero por mesa?

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2143-2021-2/Syllabus#79]
Hola! Duda bien breve. Podemos asumir que cada mesa es atendida por un, y solo un mesero?
Gracias de antemano :handshake:

**Comment by JosefaPaz** [comment]
Hola!

Sí, es un supuesto muy válido y que debe hacerse :)

**Comment by Gsalinas1506** [comment]
yaa, muchas graciass
