### ISSUE TITLE
Problemas con setup: Paso 5

### ISSUE THREAD

**Issue by Pabloski100** [IIC2143-2021-2/Syllabus#8]
Hola, al realizar el paso 5 tengo problemas con el comando:

`gem install rails -v 5.2.4`

En consola aparece:

`No se ha encontrado la orden «gem»`

Me parece raro, ya que el comando anterior que se supone instala Ruby va bien, y supongo que de ahí viene el comando gem (instale ubuntu para el curso, no se si tenga que configurar algo por eso)

**Comment by rmastudillo** [comment]
Podrías probar con lo que salé acá https://rvm.io/integration/gnome-terminal

**Comment by christianluer** [comment]
Yo lo resolví recién usando 'rvm use 2.6.6 --default'
espero te sirva

**Comment by Pabloski100** [comment]
Hola! Al final era algo raro, escribí un comando para reinstalar el comando justo anterior y ahí funciono, por si a alguien más le pasa, gracias por la ayuda
