### ISSUE TITLE
Duda con el set up

### ISSUE THREAD

**Issue by enriquerussi** [IIC2143-2021-2/Syllabus#80]
Hola, tengo una duda con el set up, específicamente en el paso 3, donde se ingresan los comandos "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable"

, y luego para verificar que rvm se instalo correctamente se ejecuta el comando "rvm -v", pero esto solo me entrega como respuesta "Command 'rvm' not found, but there are 21 similar ones.". Supongo que esto significa que no se ejecuto bien el paso anterior y no se que hacer. Pido asistencia para resolver esta situación.

**Comment by festelle** [comment]
Hola! 
Después de instalar rvm, debes cerrar y volver a abrir la consola.

Avísame si funciona!

**Comment by enriquerussi** [comment]
Hola, no funciono.

**Comment by festelle** [comment]
Intenta correr los siguientes comandos desde la consola (si estás en windows, desde ubuntu):

1- source ~/.rvm/scripts/rvm

2- type rvm | head -n 1

Si te sale de respuesta "rvm is a shell function...", debería estar funcionando

**Comment by enriquerussi** [comment]
Hola intente los pasos anteriores pero no encontré nada. 

Al escribir el comando: " source ~/.rvm/scripts/rvm"
Aparece : "-bash: /home/erussi/.rvm/scripts/rvm: No such file or directory"

Al escribir el comando: "  type rvm | head -n 1"
Aparece: "-bash: type: rvm: not found"

Luego si trato de ejecutar el comando del paso 3, ósea " gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
url -sSL https://get.rvm.io | bash -s stable"
Aparece:"gpg: keyserver receive failed: No name"

Necesito ayuda para arreglar esto por favor.
