### ISSUE TITLE
[Tarea 0] [Top_mesas]

### ISSUE THREAD

**Issue by Piolawa** [IIC2143-2021-2/Syllabus#82]
Hola,
Me confundí un poco en el cálculo del total gastado por mesa, ya que en esta issue: /issues/44, sale que en el total de la mesa viene incluido el 10% de cada persona, pero en la issue /issues/47 dice que no la debo considerar 😭

**Comment by ShescBlank** [comment]
Hola :D soy el de la issue 47, no me refería a que no se deba considerar la propina en el cálculo, sino que en ese método no modifico todavía el atributo propina de los meseros. Espero se entienda 😅

**Comment by Piolawa** [comment]
Aaah, ya entendí. Gracias! @ShescBlank
