### ISSUE TITLE
[TAREA] Orden Platillos y duda output

### ISSUE THREAD

**Issue by jfuentesg26** [IIC2143-2021-2/Syllabus#84]
Hola! Tengo dos preguntas :)
1. En el enunciado dice que los platillos se deben entregar por orden según aparecen en el archivo platillos.csv, sin embargo haciendolo así no me da el mismo output. Cuando lo hago según el orden de pedidos.csv me da lo mismo que el archivo expected_output. ¿Cual orden uso? 
2. Tengo una duda sobre el output correcto, por ejemplo, Ignacio, pide los platillos 17, 7 y 2 que tienen precios 4949, 10565, 1101 respectivamente lo que da una suma de 16615 y si le agregamos el 10% da un gasto total 18276.5 que redondeado debería dar 18277, sin embargo, el expected_output da como resultado 182778. ¿Nos guiamos por el resultado que da el archivo o el que da "haciendolo a mano"? 
Muchas gracias!!

**Comment by JosefaPaz** [comment]
Hola!

Respecto a la primera pregunta, si te da correcto siguiendo el orden de pedidos.csv entonces sigue con ese orden :)

Respecto a la segunda, debe haber sido un typo de mi parte, así que guíate con el resultado de 18277 que te da, estaría excelente así.

Éxito!!
