### ISSUE TITLE
Paso 10: rails db:create

### ISSUE THREAD

**Issue by Franco1208** [IIC2143-2021-2/Syllabus#85]
Hola, al ejecutar rails db:create me tira el siguiente error
![error10](https://user-images.githubusercontent.com/69912991/132133547-c4472899-d936-45c8-b8f6-752b073d4339.jpg)

Desde ya muchas gracias!!

**Comment by oretmj** [comment]
Hola, en una de esas no has iniciado postgresql, `sudo service postgresql start`. Si no te funciona podrías revisar las issues con las etiquetas "postgres" (se la voy a poner a esta también). En especifico te podría servir las #18 que tiene exactamente el mismo problema (o por lo menos le tira el mismo error).

**Comment by Franco1208** [comment]
Muchas gracias!!! eso era
