### ISSUE TITLE
[Tarea] - Método generar_boletas

### ISSUE THREAD

**Issue by fedezang** [IIC2143-2021-2/Syllabus#86]
Hola! tengo una duda respecto a este método. Según entiendo al generar las boletas también tengo que actualizar la propina de los meseros y el dinero/gasto de los clientes (para las instancias).
Mi duda está en que el enunciado dice "_Pueden haber instrucciones repetidas. Pueden faltar instrucciones. El orden es to- talmente arbitrario._", entonces no me queda claro como se podría, por ejemplo, ejecutar _top_mesas_ sin antes haber ejecutado _generar_boletas_, o que pasaría si ejecuta generar_boletas 2 veces, ¿Se cobraría a los clientes denuevo?

Gracias!

**Comment by JosefaPaz** [comment]
Hola!!

Las respuestas de la issue #38 puede que te sirvan! 

Exito!

**Comment by fedezang** [comment]
Perfecto gracias!
Lo único que no me queda claro de la issue #38 es que pasa si ejecuto top_mesas antes de generar_boletas, ya que si generar_boletas actualiza los atributos, en el caso de no ejecutarlo, el gasto (al momento) de cada mesa sería 0. ¿o no?
