### ISSUE TITLE
Duda Ubicación Repositorio en Windows

### ISSUE THREAD

**Issue by CrisBerriosL** [IIC2143-2021-2/Syllabus#87]
Hola! 
En la ayudantía de Git me quedó la duda de si estando en Windows utilizando wsl, es necesario que nuestros repositorios se ubiquen en la parte de Ubuntu del pc, o si es sólo una recomendación, ya que los ayudantes comentaron algo al respecto. Pregunto porque al menos tengo todos mis archivos de la universidad en la parte de documentos, y en otros ramos en los que he utilizado wsl he clonado los repositorios ahí nomás y nunca he tenido un problema. 
Para este ramo es necesario? O es solo una recomendación? Y si es recomendación cuál es la razón?

**Comment by domingo2000** [comment]
Debes tener tu repositorio clonado en el wsl, esto debido a que todo lo que instalaste en el setup se encuentra instalado en ubuntu y no en windows, por lo que debes tener el proyecto ahí para que funcione rails y todos los comandos que se deben correr para que funcione tu proyecto!
