### ISSUE TITLE
Duda con respecto a correr el programa desde el terminal

### ISSUE THREAD

**Issue by based-on-what** [IIC2143-2021-2/Syllabus#88]
Muy buenas a todos, en el enunciado dice que para correr la tarea, será con el comando en la terminal `ruby main.rb {datasets_folder} {instructions_file} {output_file}`, sin embargo, tengo una duda, ¿el archivo de instrucciones **SIEMPRE** se llamará `instructions.txt`? ¿Y las instrucciones serán siempre las mismas dentro del archivo de instrucciones?

Saludos y muchas gracias.

**Comment by JosefaPaz** [comment]
Hola!

El nombre del archivo para las instrucciones puede variar, ya que ustedes lo reciben como ARGV no debería haber problemas con esto.
Respecto a si siempre serán las mismas, te puede servir la issue #38 ! 

Éxito!!
