### ISSUE TITLE
duda aproximaciones método generar_boletas()

### ISSUE THREAD

**Issue by LucaSpiniello** [IIC2143-2021-2/Syllabus#89]
Estimados, tengo una duda sobre el comando que utilizan en el expected_output para aproximar, por ejemplo, para el caso de Ignacio que se pide los platos 2, 7 y 17, que cuestan 1211.1 , 11621.5 y 5443.9  incluyendo propina, la suma aproximando todo por exceso daría un total de 18.277 y sin embargo en el expected_output este valor debiese ser 18.278, porfavor si me podrían aclarar de donde sale esa unidad extra, muchas gracias.

**Comment by Gsalinas1506** [comment]
Encontré el mismo caso que mencionas (el cliente 6 pidiendo esos 3 platillos). **Al menos como yo calculé** fue calcular la propina platillo por platillo y **siempre** redondear hacia arriba. Me explico:
- Platillo 2: costaba 1211.1 con propina incluida. Lo aproximé a 1212
- Platillo 7: costaba 11621.5 con propina incluida. Lo aproximé a 11622
- Platillo 17: costaba 5443.9 con propina incluida. Lo aproximé a 5444

Luego sumando los costos totales, da 1212 + 11622 + 5444 = 18278, que es lo que aparece en el expected_output. Repito, así fue como la calculé yo y **creo** que de ahí sale esa unidad extra. Si alguien sabe y está seguro, porfavor confirme 🙏

**Comment by raibd** [comment]
@Gsalinas1506 Hay que calcular la propina platillo por platillo? Ahora me confundi porque en el enunciado sale que se calcula a partir del total de los platillos.

**Comment by Gsalinas1506** [comment]
Leí en un issue que daba lo mismo como lo calculabas

**Comment by JosefaPaz** [comment]
Hola! Tal como dice @Gsalinas1506 , en la issue #57 puedes encontrar la respuesta ^^

Éxito!!

**Comment by dedmu5** [comment]
> Encontré el mismo caso que mencionas (el cliente 6 pidiendo esos 3 platillos). **Al menos como yo calculé** fue calcular la propina platillo por platillo y **siempre** redondear hacia arriba. Me explico:
> 
> * Platillo 2: costaba 1211.1 con propina incluida. Lo aproximé a 1212
> * Platillo 7: costaba 11621.5 con propina incluida. Lo aproximé a 11622
> * Platillo 17: costaba 5443.9 con propina incluida. Lo aproximé a 5444
> 
> Luego sumando los costos totales, da 1212 + 11622 + 5444 = 18278, que es lo que aparece en el expected_output. Repito, así fue como la calculé yo y **creo** que de ahí sale esa unidad extra. Si alguien sabe y está seguro, porfavor confirme 🙏

Cuando hago esto me da bien para Ignacio, pero todos los demás que quedan malos con respecto al output esperado, quedan pasados en una unidad.

**Comment by fagiannoni** [comment]
> > Encontré el mismo caso que mencionas (el cliente 6 pidiendo esos 3 platillos). **Al menos como yo calculé** fue calcular la propina platillo por platillo y **siempre** redondear hacia arriba. Me explico:
> > 
> > * Platillo 2: costaba 1211.1 con propina incluida. Lo aproximé a 1212
> > * Platillo 7: costaba 11621.5 con propina incluida. Lo aproximé a 11622
> > * Platillo 17: costaba 5443.9 con propina incluida. Lo aproximé a 5444
> > 
> > Luego sumando los costos totales, da 1212 + 11622 + 5444 = 18278, que es lo que aparece en el expected_output. Repito, así fue como la calculé yo y **creo** que de ahí sale esa unidad extra. Si alguien sabe y está seguro, porfavor confirme 🙏
> 
> Cuando hago esto me da bien para Ignacio, pero todos los demás que quedan malos con respecto al output esperado, quedan pasados en una unidad.

A mi me pasaba lo mismo y después caché que era porque habían números como `16148.000000000002` y luego al redondear hacia arriba ese `...0002` me subía todo una unidad. Eso sucede por temas sobre como manejan los `float` los computadores. Lo arreglé truncando antes de ese último decimal molesto.
