### ISSUE TITLE
Problema con crear el proyecto Mac

### ISSUE THREAD

**Issue by ian-fell** [IIC2143-2021-2/Syllabus#9]
Hola!
Al intentar crear un proyecto en el paso 6 lo intenté de 2 formas:
`rails new <proyecto> --database=postgresql`
y: 
`rails new proyecto --database=postgresql`

Pero para cada uno de esos me comandos me arroja respectivamente los errores:
`zsh: no such file or directory: proyecto`
y:
`/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems.rb:281:in `find_spec_for_exe': can't find gem railties (>= 0.a) with executable rails (Gem::GemNotFoundException)`

A mi me da la impresión de que es un problema con la instalación de rails por la descripción del error, pero al correr el comando de instalación de rails me corre bien, entonces nose que hacer. Una cosa que creo que es importante mencionar es que yo instalé antes ruby con homebrew, como enseñaba el tutorial subido a canvas de ruby, ya que todavía no estaba esta guía disponible. También instalé el version manager y ruby 2.6 con esta guía una vez que la publicaron. Quizás algo tiene que ver con el problema.

**Comment by Pablok98** [comment]
¡Hola!

Si inspeccionamos la línea:

`/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems.rb:281:in`

da la impresión de que instalaste con Homebrew la versión 3 de Ruby. Según lo que comentas, si entendí bien, debes tener múltiples instalaciones de Ruby, asumo que la primera que instalaste no lo hiciste con rvm.

Para poder evaluar mejor la situación (antes de entrar en desinstalar/reinstalar), te puedo pedir que me muestres un pantallazo de la respuesta de tu consola para los siguientes comandos por favor:

1. `ruby -v`
2. `which ruby`
3. `rvm current`

Quedo atento!

**Comment by ian-fell** [comment]
<img width="566" alt="ruby -v" src="https://user-images.githubusercontent.com/62180167/130460457-6f5b63b9-57b6-4cd2-9c35-4568daf5e634.png">
<img width="559" alt="which ruby" src="https://user-images.githubusercontent.com/62180167/130460596-d15e4677-1e94-4727-80fc-9cb4b82d5555.png">
<img width="560" alt="rvm current" src="https://user-images.githubusercontent.com/62180167/130460624-3f432a33-f712-49e1-ab69-7a09a454a170.png">

Ahi van las 3 respuestas de consola en orden :)

**Comment by Pablok98** [comment]
Y ahora que reiniciaste la consola, sigue sin funcionarte?
 Creo que con `rvm reset`  y luego `rvm use 2.6` debería funcionarte. 

Lo único que me preocupa es que quede esa instalación extra de ruby, que no te traiga problemas en el futuro. Si los comandos anteriores te funcionaron, te recomiendo desinstalar el otro Ruby.

**Comment by ian-fell** [comment]
Ahora funciona, pero ocurre esto: 
<img width="567" alt="Problema proyecto" src="https://user-images.githubusercontent.com/62180167/130468011-28041228-b2f9-49ed-9c0c-18cb3316a6aa.png">

Me tira que no tenía instalado rails. Al intentar instalar rails con el comando de la guía: `gem install rails -v 5.2.4` me tira el último error, que no tengo permiso. Mi pregunta ahora es: Hay algún problema con instalar rails con el comando que me recomienda la consola (`sudo gem install rails`)? O necesita ser la versión indicada en la guía? Y de ser necesaria la versión 5.2.4, como obtengo permiso?

**Comment by Pablok98** [comment]
Utiliza el mismo comando que estás usando, pero agrégale la palabra sudo al inicio, eso debería funcionar

**Comment by ian-fell** [comment]
Si, lo encontré en internet, por eso borré el comentario, pero ahora al instalar me arroja varios errores: 
<img width="565" alt="1" src="https://user-images.githubusercontent.com/62180167/130470833-46244cad-42fa-4a19-8b64-b1490bde8fc5.png">
<img width="566" alt="2" src="https://user-images.githubusercontent.com/62180167/130470874-0ddca11c-a52e-4c5e-8327-99d9433fd0d3.png">
<img width="564" alt="3" src="https://user-images.githubusercontent.com/62180167/130470894-924474b9-4a30-4203-b624-9a5d8df48528.png">

**Comment by Pablok98** [comment]
Pueden ser varias cosas, quizás una buena idea sea que lo veamos personalmente por medio de Discord y luego dejamos acá la solución que encontremos. 

Una última cosa que podría ser, tienes Xcode instalado en tu computador? En el caso de no tenerlo, podrías correr el comando `xcode-select --install` y luego intentar instalar rails denuevo

**Comment by ian-fell** [comment]
Si, veamoslo mejor por Discord. Me mandas tu nombre de usuario? El mio tiene un par de caracteres especiales, y podría dificultar la busqueda.

**Comment by Pablok98** [comment]
Dale, mi usuario es: San Ahoria 🥕#7182

podrías en unos 20 minutos?

**Comment by ian-fell** [comment]
Si, perfecto

**Comment by panchotarud** [comment]
lo pudieron resolver? tengo el mismo problema. Al crear la base de datos me pide que instale `gem install pg -v '1.2.3'` y cuando lo intento, me tira este mismo error:(

> Si, lo encontré en internet, por eso borré el comentario, pero ahora al instalar me arroja varios errores:
> <img alt="1" width="565" src="https://user-images.githubusercontent.com/62180167/130470833-46244cad-42fa-4a19-8b64-b1490bde8fc5.png">
> <img alt="2" width="566" src="https://user-images.githubusercontent.com/62180167/130470874-0ddca11c-a52e-4c5e-8327-99d9433fd0d3.png">
> <img alt="3" width="564" src="https://user-images.githubusercontent.com/62180167/130470894-924474b9-4a30-4203-b624-9a5d8df48528.png">
