### ISSUE TITLE
[Tarea 0] Duda output

### ISSUE THREAD

**Issue by Piolawa** [IIC2143-2021-2/Syllabus#90]
Hola!
Debería afectar una instrucción a la otra?
Es que si corro por ejemplo, el método top_mesas antes del método generar_boletas me entrega resultados distintos a cuando corro top_mesas después de generar_boletas.

**Comment by JosefaPaz** [comment]
Hola!

La issue #38 te puede servir para esta pregunta :) Pero está correcto que varíen, ya que claramente el método generar_boletas modificaría atributos.

Éxito!!
