### ISSUE TITLE
[Tarea] Los clientes gastan o no gastan dinero? Posible error en expected_output

### ISSUE THREAD

**Issue by Gsalinas1506** [IIC2143-2021-2/Syllabus#91]
Hola. Mientras hacia el método `generar_boletas` me di cuenta de que, siguiendo el método de entrega de los platillos descrito en el enunciado, hay un resultado que no me calza. No se si esto puede ser debido a la forma en la que escribí la solución, o si existe un error en el documento `expected_output`.

Mi duda viene por lo siguiente: En expected_output sale que en la mesa 11, la cliente 'Maite' hizo un gasto de 18526. Esto según yo es un error, ya que según el enunciado, los platillos deben ser entregados de según su orden en `platillos.csv`, y siguiendo esa lógica, para esta clienta su gasto se reparte de la siguiente manera (considerando que ella pide los platillos 8, 25 y 33 según `pedidos.csv`):

_Clienta: Maite (id: 4; dinero: 23101)_
--> pide el platillo 8 (cuesta 4344, 4779 con propina)
El dinero que da en 18322
--> pide el platillo 25 (cuesta 10346, 11381 con propina)
El dinero que da en 6941
--> pide el platillo 33 (cuesta 12497, 13747 con propina)
El dinero no es suficiente, quedaría en negativo
----> El gasto total de Maite sería de 16160, y no de 18526 como indica el enunciado

**¿Existe alguna otra fuente de gasto desde la cual Maite haya podido gastar la diferencia que no haya considerado, o efectivamente hay un error?**
Muchas gracias de antemano 🤝 :

**Comment by JosefaPaz** [comment]
Hola!!

Si te fijas, el platillo 33 está antes que el platillo 25 en la lista de pedidos, por lo que la suma sería el platillo 8 (cuesta 4344, 4779 con propina) más el platillo 33 (cuesta 12497, 13747 con propina), y ahí te daría la suma indicada en el output :)

Éxito!!

**Comment by Gsalinas1506** [comment]
Hola. Sii, vi eso que mencionas, pero ahí me queda la duda con lo que sale en el enunciado, ya que dice que _los platillos se van entregando siguiendo el orden del archivo platillos.csv_. Entendiendo esto como entregar primero (para este ejemplo), todos los platillos de id=1, luego todos los platillos de id=2, luego los de id=3, y así sucesivamente hasta el de id=36. Siguiendo esa indicación, primero se entregaría el de id=8, luego el de id=25 y finalmente el de id=33. Entendí mal entonces la indicación de seguir el orden? :sweat_smile:

**Comment by CrisBerriosL** [comment]
Hola perdón que me meta jaja pero quizás hay un error ahí en el enunciado y en vez de que se entreguen en el orden de platillos.csv se debiesen entregar en el orden de pedidos.csv?

**Comment by jaguarKiller** [comment]
Hola! Tengo la misma duda. Está mal el enunciado o está mal el expected_output??
