### ISSUE TITLE
[TAREA] No such file or directory @ rb_sysopen - (Errno::ENOENT) 

### ISSUE THREAD

**Issue by based-on-what** [IIC2143-2021-2/Syllabus#92]
Hola a todos, tengo este gran problema porque de verdad ya no sé qué puede ser

Este es el directorio de mi tarea
![dir](https://user-images.githubusercontent.com/62000495/132272106-c2ad1dc0-36f7-476b-ba54-f17aa79aa0bc.PNG)

Y al momento de correr el programa, obtengo este error:

![errordelectura](https://user-images.githubusercontent.com/62000495/132272013-9dafb645-b94c-4b90-a435-af4d2e57e726.PNG)

Sinceramente no se me ocurre nada más con este problema, ¿qué puedo hacer para que el archivo pueda ser leído?

Saludos y gracias

**Comment by based-on-what** [comment]
Olvidé mencionar que el código está así:

`carpeta = ARGV[0]
instrucciones = ARGV[1]
output = ARGV[2]

puts instrucciones

file_object = File.open(instrucciones, "r")`

**Comment by Lord-Kelsier** [comment]
A primera vista veo que escribiste `main.arb` en lugar de `main.rb` en la consola y el archivo tambien es `.arb`
