### ISSUE TITLE
[Guía/Set up] [Paso 10 / 11]

### ISSUE THREAD

**Issue by tsunayoshi21** [IIC2143-2021-2/Syllabus#93]
Hola, cuando intento ejecutar el comando "rails db:create" en la consola de ubuntu me tira el siguiente error:
![image](https://user-images.githubusercontent.com/69870567/132283671-dcc5038b-ce6e-45dc-a396-f62c9d549c39.png)

Intente de todas formas ejecutar "rails s" y al abrir el local host me sale la siguiente pagina:
![image](https://user-images.githubusercontent.com/69870567/132283764-fb7adb7d-504d-4a2d-87c1-225d82b93e71.png)

Alguna idea de como solucionarlo? Busque en stack pero no encontre mucho :/

**Comment by tsunayoshi21** [comment]
Tambien, intente correr "rake db:create" y me sale lo siguiente:
![image](https://user-images.githubusercontent.com/69870567/132284677-99536253-2351-4c59-80bf-2685f669996d.png)

**Comment by festelle** [comment]
Hola, te aseguraste que el servidor de postgres estuviera corriendo? Si no, intenta poner "sudo service postgresql start" para comenzar el servidor.

Si eso no funciona, puedes revisar el port al que está conectado postgres?

**Comment by festelle** [comment]
Con el comando "sudo service postgresql status"

Si muestra que estás en el port 5432 no hay problemas con el port , pero si sale cualquier otro número (normalmente sale 5433 si no es 5432) entonces ese debe ser el problema.


Me avisas qué te aparece!

**Comment by tsunayoshi21** [comment]
Lo intente, y me salio esto:
![image](https://user-images.githubusercontent.com/69870567/132435820-5c5d41a4-75e5-441f-b6be-de98963ed1be.png)
Parece que el port no es el problema :(

**Comment by festelle** [comment]
Quizás sea error de los binarios, corre el siguiente comando en ubuntu, en la carpeta raíz de la app (en tu caso web whatsapp):

rake rails:update:bin

Y pon "y" cuando te pida autorización oara reemplazar los binarios.

Si después de esto no funciona, puedes probar hacer otro proyecto de rails?

**Comment by tsunayoshi21** [comment]
Hola, disculpa, no había visto esta respuesta y me deje.

Hice lo que me dices y me sale lo siguiente:
![image](https://user-images.githubusercontent.com/69870567/133362858-25e539fa-3863-4b94-b9b4-f6218821c8f4.png)


En ningún momento me pide aceptar nada:(

**Comment by dedmu5** [comment]
![image](https://user-images.githubusercontent.com/65060602/134583303-f91ef698-731d-4d80-9c3a-1c79073c6665.png)
Creo que ahí está el error
