### ISSUE TITLE
Duda Ayudantia

### ISSUE THREAD

**Issue by Piolawa** [IIC2143-2021-2/Syllabus#94]
Hola!
En la ayudantía 3, mostraban como clonar el repositorio, y luego corrian los siguientes comandos:
```
rails db:create
rails s
```

Cloné el repositorio que nos asignaron por grupo, corrí el primer comando y me sale esto:

![image](https://user-images.githubusercontent.com/80898544/132419978-2002d6d8-7c28-46e7-9343-49935ba25018.png)

Recuerdo que eso me salia cuando aun estaba instalando ruby en ubuntu, pero ya he seguido todos los pasos del setup, y logré instalar todo, mi pregunta es si debo hacer los mismos pasos del setup para instalar ruby pero en el repositorio local en mi computador, hoy hay otro problema? :(

**Comment by oretmj** [comment]
Hola, si te fijas al correr el comando `ls` en la consola dentro de la carpeta del repositorio de tu grupo podrás ver que solo se encuentre el Readme. Esto es porque aun no hay un proyecto dentro del repositorio, la idea es que ustedes lo creen (ahi tienen que utilizar el comando de `rails new <nombre proyecto> --database=postgresql `). Revisa la guia del Setup para que te sea más claro. 
Cuando tengas el proyecto creado ya podrías usar los comandos de `rails db:create` y `rails s`.

**Comment by Piolawa** [comment]
Muchas gracias!

**Comment by OrregoSilva** [comment]
En general es una persona quien crea el proyecto y lo sube a Github para que los demás lo clonen, lo que si, cada uno de manera independiente tiene que crear la base de datos ya que estas son locales.
