### ISSUE TITLE
Guía set up paso 3/11

### ISSUE THREAD

**Issue by enriquerussi** [IIC2143-2021-2/Syllabus#96]
Hola tengo problemas para realizar el set up en el paso 3. Al intentar ejecutar el comando:

"gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://get.rvm.io | bash -s stable"

Me aparece:

"gpg: keyserver receive failed: No name"

Y luego:

"Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made Fri Jan 15 15:46:22 2021 -03
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Can't check signature: No public key
GPG signature verification failed for '/home/erussi/.rvm/archives/rvm-1.29.12.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

In case of further problems with validation please refer to https://rvm.io/rvm/security"

Necesito asistencia para resolver esta situación. Muchas gracias.

**Comment by PDominguezW** [comment]
Intenta con esto https://stackoverflow.com/questions/29218225/key-issue-with-installing-rvm-ruby-version-manager.
