### ISSUE TITLE
Como hacer para que variables locales no cambien al usarlas en métodos de clases?

### ISSUE THREAD

**Issue by mmunoz12** [IIC2143-2021-2/Syllabus#97]
Hola! Me he revisado todas las clases y ayudantías y no he podido resolver esto y quizás es algo super fácil :( . Me pasa que tengo el hash_mesas que parte siendo un hash con las llaves como mesas y sus valores son listas vacías. Al utilizarlo en la primer método de la clase Simulación, todo bien, pero el problema es que para la segunda función el hash_mesas esta cambiado según lo que ocurrió en el método anterior. Mi plan es que este no cambie (al menos no fuera de la clase) ya que dentro de estos métodos lo tengo instanciado como variable local (ya que aquí sí lo modifico), pero supongo que como Ruby retorna la última línea, me lo termina actualizando igual. Quiero que todas las modificaciones que se hagan al hash se “queden” dentro de su respectiva función, no que lo cambie fuera de la clase también. Espero que se haya entendido! Gracias de antemano :)

Foto de ejemplo, en cada uno de esos print el hash_mesas aparece distinto:
<img width="516" alt="Captura de Pantalla 2021-09-08 a la(s) 17 53 10" src="https://user-images.githubusercontent.com/62077530/132584216-870e2a0a-8250-433c-92b0-bf86b55fc32b.png">

**Comment by Lord-Kelsier** [comment]
Creo que entiendo tu problema, aunque la tarea ya paso, te explico para un futuro.

## Solucion 
Genera una copia.
```ruby
hash_copia = hash_original.clone
```
## Explicacion

En python ocurria lo mismo con las listas, si haces:
```python
lista_A = [ 1, 2]
lista_B = lista_A
lista_B.append(3)
print(lista_A) 
=> [ 1, 2, 3]
```
A pesar de haber hecho un `append`  a la `lista_B` la `lista_A` tambien se modifica. Esto se debe a que los hashes, las listas y muchas otras estructuras de datos pertenecen al tipo de dato referenciado (*creo que tiene un nombre mas bonito pero no lo recuerdo*), es decir, se le asigna un valor en memoria y cada instancia es una referencia a ese valor. La solucion al igual que en python era ocupar un metodo para hacer una copia que contenga otro valor en memoria diferente(para python era `lista_C = lista_A.copy()` ).
