### ISSUE TITLE
Error al hacer git clone

### ISSUE THREAD

**Issue by claudiosalvador** [IIC2143-2021-2/Syllabus#98]
Hola! Al tratar de clonar el repositorio de mi grupo me sale el siguiente error:

![imagen_2021-09-08_214546](https://user-images.githubusercontent.com/48532736/132604054-3a530a1f-c862-4974-bef7-0b9e4248a521.png)

Esto solo pasa desde la terminal de Ubuntu, en la terminal de Windows pude hacerlo sin ningún problema. He buscado y probado varias alternativas que encontré en internet pero nada ha funcionado. Alguien sabe que podría ser y como puedo solucionarlo?

**Comment by OrregoSilva** [comment]
Lo mas probable es que en Ubuntu no tienes registradas tus credenciales, como el mail y usuario, y ya que el repositorio de tu grupo es privado, es necesario tener esas cosas. De todas formas puedes perfectamente clonar con la terminal de Windows y trabajar desde la de Ubuntu, que es lo que usualmente hago yo. Para abrir la consola de Ubuntu en el lugar donde clonas el repositorio (por ejemplo una carpeta en el escritorio) escribe `wsl` al igual que en la imagen y con eso debería bastar.


![image](https://user-images.githubusercontent.com/62146691/132931489-2b07c0b0-cadc-4cdf-bf26-1f156db9d550.png)

**Comment by claudiosalvador** [comment]
@OrregoSilva perfecto, muchas gracias por tu respuesta!
