### ISSUE TITLE
Configuaración Rubocop proyecto

### ISSUE THREAD

**Issue by Jamesmoreno21** [IIC2143-2021-2/Syllabus#99]
Hola! Con mi equipo hemos estado investigando como configurar Rubocop, encontramos que se instalaba una gema y se podía crear un archivo .yml, pero también existe una extensión en VSCode. El problema en ambos casos es que no sabemos configurar las reglas que tenemos definidas y no sé si hay alguna página para guiarnos con lo básico tipo: máximo de líneas, máximo de caracteres por línea, reglas para variables y clases y cosas así. 
Agradeceríamos mucho un poco de orientación!

Saludos!

**Comment by Lord-Kelsier** [comment]
https://docs.rubocop.org/rubocop/1.20/index.html
